-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Windows.Forms.DataGridRow.DataGridRowAccessibleObject;
with MSSyst.Reflection.IReflect;
with type MSSyst.Runtime.Remoting.ObjRef.Ref is access;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.Object.Ref is access;
with type MSSyst.Drawing.Rectangle.Valuetype is tagged;
with type MSSyst.String.Ref is access;
with type MSSyst.Windows.Forms.AccessibleObject.Ref is access;
with MSSyst.Windows.Forms.AccessibleRole;
with MSSyst.Windows.Forms.AccessibleStates;
with type MSSyst.String.Ref_addrof is access;
with MSSyst.Windows.Forms.AccessibleNavigation;
with MSSyst.Windows.Forms.AccessibleSelection;
with type MSSyst.Windows.Forms.DataGridRow.Ref is access;
package MSSyst.Windows.Forms.DataGridRelationshipRow.DataGridRelationshipRowAccessibleObject is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.Windows.Forms.DataGridRow.DataGridRowAccessibleObject.Typ
         and MSSyst.Reflection.IReflect.Typ
   with record
      null;
   end record;
   function new_DataGridRelationshipRowAccessibleObject(
      This : Ref := null;
      owner : MSSyst.Windows.Forms.DataGridRow.Ref) return Ref;
   procedure DoDefaultAction(
      This : access Typ);
   function get_DefaultAction(
      This : access Typ) return MSSyst.String.Ref;
   function get_State(
      This : access Typ) return MSSyst.Windows.Forms.AccessibleStates.Valuetype;
   function GetFocused(
      This : access Typ) return MSSyst.Windows.Forms.AccessibleObject.Ref;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_DataGridRelationshipRowAccessibleObject);
   pragma Import(MSIL,DoDefaultAction,"DoDefaultAction");
   pragma Import(MSIL,get_DefaultAction,"get_DefaultAction");
   pragma Import(MSIL,get_State,"get_State");
   pragma Import(MSIL,GetFocused,"GetFocused");
end MSSyst.Windows.Forms.DataGridRelationshipRow.DataGridRelationshipRowAccessibleObject;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Windows.Forms.DataGridRelationshipRow.DataGridRelationshipRowAccessibleObject,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.DataGridRelationshipRow/DataGridRelationshipRowAccessibleObject");
