-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Object;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.Object.Ref_array is access;
with type MSSyst.Reflection.Assembly.Ref is access;
with type MSSyst.String.Ref is access;
with type MSSyst.Reflection.FieldInfo.Ref is access;
package MSSyst.Runtime.Serialization.Formatters.InternalST is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.Object.Typ   with record
      null;
   end record;
   procedure InfoSoap(
      messages : MSSyst.Object.Ref_array);
   function LoadAssemblyFromString(
      assemblyString : MSSyst.String.Ref) return MSSyst.Reflection.Assembly.Ref;
   procedure SerializationSetValue(
      fi : MSSyst.Reflection.FieldInfo.Ref;
      target : MSSyst.Object.Ref;
      value : MSSyst.Object.Ref);
   procedure Soap(
      messages : MSSyst.Object.Ref_array);
   procedure SoapAssert(
      condition : Standard.Boolean;
      message : MSSyst.String.Ref);
   function SoapCheckEnabled return Standard.Boolean;
private
   pragma Convention(MSIL,Typ);
   pragma Import(MSIL,InfoSoap,"InfoSoap");
   pragma Import(MSIL,LoadAssemblyFromString,"LoadAssemblyFromString");
   pragma Import(MSIL,SerializationSetValue,"SerializationSetValue");
   pragma Import(MSIL,Soap,"Soap");
   pragma Import(MSIL,SoapAssert,"SoapAssert");
   pragma Import(MSIL,SoapCheckEnabled,"SoapCheckEnabled");
end MSSyst.Runtime.Serialization.Formatters.InternalST;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Runtime.Serialization.Formatters.InternalST,
   ".ver 2.0.0.0 .publickeytoken=( 96 9d b8 05 3d 33 22 ac )",
   "[mscorlib]System.Runtime.Serialization.Formatters.InternalST");
