-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with type MSSyst.Object.Ref is access;
with type MSSyst.Data.DataColumn.Ref is access;
with type MSSyst.Data.DataRow.Ref is access;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.String.Ref is access;
with MSSyst.EventArgs;
package MSSyst.Data.DataColumnChangeEventArgs is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Arr1 is array(Natural range <>) of Ref;
   type Ref_Array is access all Arr1;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.EventArgs.Typ with record
      null;
   end record;
   function new_DataColumnChangeEventArgs(
      This : Ref := null;
      row : MSSyst.Data.DataRow.Ref;
      column : MSSyst.Data.DataColumn.Ref;
      value : MSSyst.Object.Ref) return Ref;
   function get_Column(
      This : access Typ) return MSSyst.Data.DataColumn.Ref;
   function get_ProposedValue(
      This : access Typ) return MSSyst.Object.Ref;
   function get_Row(
      This : access Typ) return MSSyst.Data.DataRow.Ref;
   procedure set_ProposedValue(
      This : access Typ;
      value : MSSyst.Object.Ref);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_DataColumnChangeEventArgs);
   pragma Import(MSIL,get_Column,"get_Column");
   pragma Import(MSIL,get_ProposedValue,"get_ProposedValue");
   pragma Import(MSIL,get_Row,"get_Row");
   pragma Import(MSIL,set_ProposedValue,"set_ProposedValue");
end MSSyst.Data.DataColumnChangeEventArgs;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Data.DataColumnChangeEventArgs,
   ".ver 1:0:5000:0 .publickeytoken=( 96 9d b8 05 3d 33 22 ac )",
   "[System.Data]System.Data.DataColumnChangeEventArgs");
