-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Object;
with MSSyst.Runtime.InteropServices.uMethodRental;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.String.Ref is access;
package MSSyst.Reflection.Emit.MethodRental is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.Object.Typ
         and MSSyst.Runtime.InteropServices.uMethodRental.Typ
   with record
      null;
   end record;
   JitOnDemand : Integer;
   pragma Import(MSIL,JitOnDemand,"JitOnDemand");
   JitImmediate : Integer;
   pragma Import(MSIL,JitImmediate,"JitImmediate");
   procedure SwapMethodBody(
      cls : MSSyst.Type_k.Ref;
      methodtoken : Integer;
      rgIL : MSIL_Types.native_int;
      methodSize : Integer;
      flags : Integer);
private
   pragma Convention(MSIL,Typ);
   pragma Import(MSIL,SwapMethodBody,"SwapMethodBody");
end MSSyst.Reflection.Emit.MethodRental;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Reflection.Emit.MethodRental,
   ".ver 2.0.0.0 .publickeytoken=( 96 9d b8 05 3d 33 22 ac )",
   "[mscorlib]System.Reflection.Emit.MethodRental");
