-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Object;
with type MSSyst.Drawing.Image.Ref is access;
with type MSSyst.EventHandler.Ref is access;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.String.Ref is access;
package MSSyst.Drawing.ImageAnimator is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.Object.Typ   with record
      null;
   end record;
   procedure Animate(
      image : MSSyst.Drawing.Image.Ref;
      onFrameChangedHandler : MSSyst.EventHandler.Ref);
   function CanAnimate(
      image : MSSyst.Drawing.Image.Ref) return Standard.Boolean;
   procedure StopAnimate(
      image : MSSyst.Drawing.Image.Ref;
      onFrameChangedHandler : MSSyst.EventHandler.Ref);
   procedure UpdateFrames(
      image : MSSyst.Drawing.Image.Ref);
   procedure UpdateFrames;
private
   pragma Convention(MSIL,Typ);
   pragma Import(MSIL,Animate,"Animate");
   pragma Import(MSIL,CanAnimate,"CanAnimate");
   pragma Import(MSIL,StopAnimate,"StopAnimate");
   pragma Import(MSIL,UpdateFrames,"UpdateFrames");
end MSSyst.Drawing.ImageAnimator;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Drawing.ImageAnimator,
   ".ver 2:0:0:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[System.Drawing]System.Drawing.ImageAnimator");
