-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Object;
with MSSyst.Windows.Forms.BatteryChargeStatus;
with MSSyst.Windows.Forms.PowerLineStatus;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.String.Ref is access;
package MSSyst.Windows.Forms.PowerStatus is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.Object.Typ   with record
      null;
   end record;
   function get_BatteryChargeStatus(
      This : access Typ) return MSSyst.Windows.Forms.BatteryChargeStatus.Valuetype;
   function get_BatteryFullLifetime(
      This : access Typ) return Integer;
   function get_BatteryLifePercent(
      This : access Typ) return Float;
   function get_BatteryLifeRemaining(
      This : access Typ) return Integer;
   function get_PowerLineStatus(
      This : access Typ) return MSSyst.Windows.Forms.PowerLineStatus.Valuetype;
private
   pragma Convention(MSIL,Typ);
   pragma Import(MSIL,get_BatteryChargeStatus,"get_BatteryChargeStatus");
   pragma Import(MSIL,get_BatteryFullLifetime,"get_BatteryFullLifetime");
   pragma Import(MSIL,get_BatteryLifePercent,"get_BatteryLifePercent");
   pragma Import(MSIL,get_BatteryLifeRemaining,"get_BatteryLifeRemaining");
   pragma Import(MSIL,get_PowerLineStatus,"get_PowerLineStatus");
end MSSyst.Windows.Forms.PowerStatus;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Windows.Forms.PowerStatus,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.PowerStatus");
