-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Object;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.String.Ref is access;
package MSSyst.ComponentModel.Design.Serialization.ContextStack is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.Object.Typ   with record
      null;
   end record;
   function new_ContextStack(
      This : Ref := null) return Ref;
   procedure Append(
      This : access Typ;
      context : MSSyst.Object.Ref);
   function get_Current(
      This : access Typ) return MSSyst.Object.Ref;
   function get_Item(
      This : access Typ;
      level : Integer) return MSSyst.Object.Ref;
   function get_Item(
      This : access Typ;
      type_k : MSSyst.Type_k.Ref) return MSSyst.Object.Ref;
   function Pop(
      This : access Typ) return MSSyst.Object.Ref;
   procedure Push(
      This : access Typ;
      context : MSSyst.Object.Ref);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_ContextStack);
   pragma Import(MSIL,Append,"Append");
   pragma Import(MSIL,get_Current,"get_Current");
   pragma Import(MSIL,get_Item,"get_Item");
   pragma Import(MSIL,Pop,"Pop");
   pragma Import(MSIL,Push,"Push");
end MSSyst.ComponentModel.Design.Serialization.ContextStack;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.ComponentModel.Design.Serialization.ContextStack,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System]System.ComponentModel.Design.Serialization.ContextStack");
