-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.ValueType;
with type MSSyst.Object.Ref is access;
with type MSSyst.RuntimeFieldHandle.Valuetype is tagged;
with type MSSyst.RuntimeMethodHandle.Valuetype is tagged;
with type MSSyst.RuntimeTypeHandle.Valuetype is tagged;
with type MSSyst.Type_k.Ref is access;
with MSSyst.RuntimeTypeHandle;
with type MSSyst.String.Ref is access;
package MSSyst.ModuleHandle is
   type ValueType is new MSSyst.ValueType.Typ with null record;
   type ValueType_Arr is array (Natural range <>) of ValueType; -- start at 0
   type ValueType_Array is access all ValueType_Arr;
   type ValueType_addrof is access all ValueType;
   type ValueType_array_addrof is access all ValueType_Array;
   function Equals(
      This : Valuetype;
      handle : MSSyst.ModuleHandle.Valuetype) return Standard.Boolean;
   function Equals(
      This : Valuetype;
      obj : MSSyst.Object.Ref) return Standard.Boolean;
   function get_MDStreamVersion(
      This : Valuetype) return Integer;
   function GetHashCode(
      This : Valuetype) return Integer;
   function GetRuntimeFieldHandleFromMetadataToken(
      This : Valuetype;
      fieldToken : Integer) return MSSyst.RuntimeFieldHandle.Valuetype;
   function GetRuntimeMethodHandleFromMetadataToken(
      This : Valuetype;
      methodToken : Integer) return MSSyst.RuntimeMethodHandle.Valuetype;
   function GetRuntimeTypeHandleFromMetadataToken(
      This : Valuetype;
      typeToken : Integer) return MSSyst.RuntimeTypeHandle.Valuetype;
   function op_Equality(
      left : MSSyst.ModuleHandle.Valuetype;
      right : MSSyst.ModuleHandle.Valuetype) return Standard.Boolean;
   function op_Inequality(
      left : MSSyst.ModuleHandle.Valuetype;
      right : MSSyst.ModuleHandle.Valuetype) return Standard.Boolean;
   function ResolveFieldHandle(
      This : Valuetype;
      fieldToken : Integer) return MSSyst.RuntimeFieldHandle.Valuetype;
   function ResolveFieldHandle(
      This : Valuetype;
      fieldToken : Integer;
      typeInstantiationContext : MSSyst.RuntimeTypeHandle.Valuetype_array;
      methodInstantiationContext : MSSyst.RuntimeTypeHandle.Valuetype_array) return MSSyst.RuntimeFieldHandle.Valuetype;
   function ResolveMethodHandle(
      This : Valuetype;
      methodToken : Integer;
      typeInstantiationContext : MSSyst.RuntimeTypeHandle.Valuetype_array;
      methodInstantiationContext : MSSyst.RuntimeTypeHandle.Valuetype_array) return MSSyst.RuntimeMethodHandle.Valuetype;
   function ResolveMethodHandle(
      This : Valuetype;
      methodToken : Integer) return MSSyst.RuntimeMethodHandle.Valuetype;
   function ResolveTypeHandle(
      This : Valuetype;
      typeToken : Integer) return MSSyst.RuntimeTypeHandle.Valuetype;
   function ResolveTypeHandle(
      This : Valuetype;
      typeToken : Integer;
      typeInstantiationContext : MSSyst.RuntimeTypeHandle.Valuetype_array;
      methodInstantiationContext : MSSyst.RuntimeTypeHandle.Valuetype_array) return MSSyst.RuntimeTypeHandle.Valuetype;
private
   pragma Import(MSIL,Equals,"Equals");
   pragma Import(MSIL,get_MDStreamVersion,"get_MDStreamVersion");
   pragma Import(MSIL,GetHashCode,"GetHashCode");
   pragma Import(MSIL,GetRuntimeFieldHandleFromMetadataToken,"GetRuntimeFieldHandleFromMetadataToken");
   pragma Import(MSIL,GetRuntimeMethodHandleFromMetadataToken,"GetRuntimeMethodHandleFromMetadataToken");
   pragma Import(MSIL,GetRuntimeTypeHandleFromMetadataToken,"GetRuntimeTypeHandleFromMetadataToken");
   pragma Import(MSIL,op_Equality,"op_Equality");
   pragma Import(MSIL,op_Inequality,"op_Inequality");
   pragma Import(MSIL,ResolveFieldHandle,"ResolveFieldHandle");
   pragma Import(MSIL,ResolveMethodHandle,"ResolveMethodHandle");
   pragma Import(MSIL,ResolveTypeHandle,"ResolveTypeHandle");
end MSSyst.ModuleHandle;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.ModuleHandle,
   ".ver 2.0.0.0 .publickeytoken=( 96 9d b8 05 3d 33 22 ac )",
   "[mscorlib]System.ModuleHandle");
