-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.ComponentModel.Component;
with MSSyst.ComponentModel.IComponent;
with MSSyst.ComponentModel.ISynchronizeInvoke;
with MSSyst.Windows.Forms.IWin32Window;
with MSSyst.Windows.Forms.IBindableComponent;
with type MSSyst.EventHandler.Ref is access;
with type MSSyst.Windows.Forms.UICuesEventHandler.Ref is access;
with type MSSyst.Windows.Forms.ControlEventHandler.Ref is access;
with type MSSyst.Windows.Forms.DragEventHandler.Ref is access;
with type MSSyst.Windows.Forms.GiveFeedbackEventHandler.Ref is access;
with type MSSyst.Windows.Forms.HelpEventHandler.Ref is access;
with type MSSyst.Windows.Forms.InvalidateEventHandler.Ref is access;
with type MSSyst.Windows.Forms.KeyEventHandler.Ref is access;
with type MSSyst.Windows.Forms.KeyPressEventHandler.Ref is access;
with type MSSyst.Windows.Forms.LayoutEventHandler.Ref is access;
with type MSSyst.Windows.Forms.MouseEventHandler.Ref is access;
with type MSSyst.Windows.Forms.PaintEventHandler.Ref is access;
with type MSSyst.Windows.Forms.PreviewKeyDownEventHandler.Ref is access;
with type MSSyst.Windows.Forms.QueryAccessibilityHelpEventHandler.Ref is access;
with type MSSyst.Windows.Forms.QueryContinueDragEventHandler.Ref is access;
with type MSSyst.ComponentModel.CancelEventHandler.Ref is access;
with type MSSyst.IAsyncResult.Ref is access;
with type MSSyst.Delegate.Ref is access;
with type MSSyst.Object.Ref_array is access;
with type MSSyst.Drawing.Graphics.Ref is access;
with type MSSyst.Runtime.Remoting.ObjRef.Ref is access;
with type MSSyst.Type_k.Ref is access;
with MSSyst.Windows.Forms.DragDropEffects;
with type MSSyst.Object.Ref is access;
with type MSSyst.Drawing.Bitmap.Ref is access;
with type MSSyst.Drawing.Rectangle.Valuetype is tagged;
with type MSSyst.Windows.Forms.Form.Ref is access;
with type MSSyst.Windows.Forms.AccessibleObject.Ref is access;
with type MSSyst.String.Ref is access;
with MSSyst.Windows.Forms.AccessibleRole;
with MSSyst.Windows.Forms.AnchorStyles;
with type MSSyst.Drawing.Point.Valuetype is tagged;
with type MSSyst.Drawing.Color.Valuetype is tagged;
with type MSSyst.Drawing.Image.Ref is access;
with MSSyst.Windows.Forms.ImageLayout;
with type MSSyst.Windows.Forms.BindingContext.Ref is access;
with type MSSyst.Drawing.Size.Valuetype is tagged;
with type MSSyst.ComponentModel.IContainer.Ref is access;
with type MSSyst.Windows.Forms.ContextMenu.Ref is access;
with type MSSyst.Windows.Forms.ContextMenuStrip.Ref is access;
with type MSSyst.Windows.Forms.Control.ControlCollection.Ref is access;
with type MSSyst.Windows.Forms.Cursor.Ref is access;
with type MSSyst.Windows.Forms.ControlBindingsCollection.Ref is access;
with type MSSyst.Drawing.Font.Ref is access;
with MSSyst.Windows.Forms.DockStyle;
with MSSyst.Windows.Forms.ImeMode;
with type MSSyst.Windows.Forms.Layout.LayoutEngine.Ref is access;
with type MSSyst.Windows.Forms.Padding.Valuetype is tagged;
with MSSyst.Windows.Forms.Keys;
with MSSyst.Windows.Forms.MouseButtons;
with type MSSyst.Drawing.Region.Ref is access;
with MSSyst.Windows.Forms.RightToLeft;
with type MSSyst.ComponentModel.ISite.Ref is access;
with type MSSyst.Windows.Forms.IWindowTarget.Ref is access;
with MSSyst.Windows.Forms.GetChildAtPointSkip;
with type MSSyst.Windows.Forms.IContainerControl.Ref is access;
with MSSyst.Windows.Forms.PreProcessControlState;
with MSSyst.Windows.Forms.Message;
with type MSSyst.Drawing.SizeF.Valuetype is tagged;
with MSSyst.Windows.Forms.BoundsSpecified;
package MSSyst.Windows.Forms.Control is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.ComponentModel.Component.Typ
         and MSSyst.ComponentModel.IComponent.Typ
         and MSSyst.ComponentModel.ISynchronizeInvoke.Typ
         and MSSyst.Windows.Forms.IWin32Window.Typ
         and MSSyst.Windows.Forms.IBindableComponent.Typ
   with record
      null;
   end record;
   function new_Control(
      This : Ref := null) return Ref;
   function new_Control(
      This : Ref := null;
      text : MSSyst.String.Ref) return Ref;
   function new_Control(
      This : Ref := null;
      text : MSSyst.String.Ref;
      left : Integer;
      top : Integer;
      width : Integer;
      height : Integer) return Ref;
   function new_Control(
      This : Ref := null;
      parent : MSSyst.Windows.Forms.Control.Ref;
      text : MSSyst.String.Ref) return Ref;
   function new_Control(
      This : Ref := null;
      parent : MSSyst.Windows.Forms.Control.Ref;
      text : MSSyst.String.Ref;
      left : Integer;
      top : Integer;
      width : Integer;
      height : Integer) return Ref;
   procedure add_AutoSizeChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_BackColorChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_BackgroundImageChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_BackgroundImageLayoutChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_BindingContextChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_CausesValidationChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_ChangeUICues(
      This : access Typ;
      value : MSSyst.Windows.Forms.UICuesEventHandler.Ref);
   procedure add_Click(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_ClientSizeChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_ContextMenuChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_ContextMenuStripChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_ControlAdded(
      This : access Typ;
      value : MSSyst.Windows.Forms.ControlEventHandler.Ref);
   procedure add_ControlRemoved(
      This : access Typ;
      value : MSSyst.Windows.Forms.ControlEventHandler.Ref);
   procedure add_CursorChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_DockChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_DoubleClick(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_DragDrop(
      This : access Typ;
      value : MSSyst.Windows.Forms.DragEventHandler.Ref);
   procedure add_DragEnter(
      This : access Typ;
      value : MSSyst.Windows.Forms.DragEventHandler.Ref);
   procedure add_DragLeave(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_DragOver(
      This : access Typ;
      value : MSSyst.Windows.Forms.DragEventHandler.Ref);
   procedure add_EnabledChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_Enter(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_FontChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_ForeColorChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_GiveFeedback(
      This : access Typ;
      value : MSSyst.Windows.Forms.GiveFeedbackEventHandler.Ref);
   procedure add_GotFocus(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_HandleCreated(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_HandleDestroyed(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_HelpRequested(
      This : access Typ;
      value : MSSyst.Windows.Forms.HelpEventHandler.Ref);
   procedure add_ImeModeChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_Invalidated(
      This : access Typ;
      value : MSSyst.Windows.Forms.InvalidateEventHandler.Ref);
   procedure add_KeyDown(
      This : access Typ;
      value : MSSyst.Windows.Forms.KeyEventHandler.Ref);
   procedure add_KeyPress(
      This : access Typ;
      value : MSSyst.Windows.Forms.KeyPressEventHandler.Ref);
   procedure add_KeyUp(
      This : access Typ;
      value : MSSyst.Windows.Forms.KeyEventHandler.Ref);
   procedure add_Layout(
      This : access Typ;
      value : MSSyst.Windows.Forms.LayoutEventHandler.Ref);
   procedure add_Leave(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_LocationChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_LostFocus(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_MarginChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_MouseCaptureChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_MouseClick(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure add_MouseDoubleClick(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure add_MouseDown(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure add_MouseEnter(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_MouseHover(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_MouseLeave(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_MouseMove(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure add_MouseUp(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure add_MouseWheel(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure add_Move(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_PaddingChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_Paint(
      This : access Typ;
      value : MSSyst.Windows.Forms.PaintEventHandler.Ref);
   procedure add_ParentChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_PreviewKeyDown(
      This : access Typ;
      value : MSSyst.Windows.Forms.PreviewKeyDownEventHandler.Ref);
   procedure add_QueryAccessibilityHelp(
      This : access Typ;
      value : MSSyst.Windows.Forms.QueryAccessibilityHelpEventHandler.Ref);
   procedure add_QueryContinueDrag(
      This : access Typ;
      value : MSSyst.Windows.Forms.QueryContinueDragEventHandler.Ref);
   procedure add_RegionChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_Resize(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_RightToLeftChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_SizeChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_StyleChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_SystemColorsChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_TabIndexChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_TabStopChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_TextChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_Validated(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure add_Validating(
      This : access Typ;
      value : MSSyst.ComponentModel.CancelEventHandler.Ref);
   procedure add_VisibleChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   function BeginInvoke(
      This : access Typ;
      method : MSSyst.Delegate.Ref) return MSSyst.IAsyncResult.Ref;
   function BeginInvoke(
      This : access Typ;
      method : MSSyst.Delegate.Ref;
      args : MSSyst.Object.Ref_array) return MSSyst.IAsyncResult.Ref;
   procedure BringToFront(
      This : access Typ);
   function Contains(
      This : access Typ;
      ctl : MSSyst.Windows.Forms.Control.Ref) return Standard.Boolean;
   procedure CreateControl(
      This : access Typ);
   function CreateGraphics(
      This : access Typ) return MSSyst.Drawing.Graphics.Ref;
   function DoDragDrop(
      This : access Typ;
      data : MSSyst.Object.Ref;
      allowedEffects : MSSyst.Windows.Forms.DragDropEffects.Valuetype) return MSSyst.Windows.Forms.DragDropEffects.Valuetype;
   procedure DrawToBitmap(
      This : access Typ;
      bitmap : MSSyst.Drawing.Bitmap.Ref;
      targetBounds : MSSyst.Drawing.Rectangle.Valuetype);
   function EndInvoke(
      This : access Typ;
      asyncResult : MSSyst.IAsyncResult.Ref) return MSSyst.Object.Ref;
   function FindForm(
      This : access Typ) return MSSyst.Windows.Forms.Form.Ref;
   function Focus(
      This : access Typ) return Standard.Boolean;
   function FromChildHandle(
      handle : MSIL_Types.native_int) return MSSyst.Windows.Forms.Control.Ref;
   function FromHandle(
      handle : MSIL_Types.native_int) return MSSyst.Windows.Forms.Control.Ref;
   function get_AccessibilityObject(
      This : access Typ) return MSSyst.Windows.Forms.AccessibleObject.Ref;
   function get_AccessibleDefaultActionDescription(
      This : access Typ) return MSSyst.String.Ref;
   function get_AccessibleDescription(
      This : access Typ) return MSSyst.String.Ref;
   function get_AccessibleName(
      This : access Typ) return MSSyst.String.Ref;
   function get_AccessibleRole(
      This : access Typ) return MSSyst.Windows.Forms.AccessibleRole.Valuetype;
   function get_AllowDrop(
      This : access Typ) return Standard.Boolean;
   function get_Anchor(
      This : access Typ) return MSSyst.Windows.Forms.AnchorStyles.Valuetype;
   function get_AutoScrollOffset(
      This : access Typ) return MSSyst.Drawing.Point.Valuetype;
   function get_AutoSize(
      This : access Typ) return Standard.Boolean;
   function get_BackColor(
      This : access Typ) return MSSyst.Drawing.Color.Valuetype;
   function get_BackgroundImage(
      This : access Typ) return MSSyst.Drawing.Image.Ref;
   function get_BackgroundImageLayout(
      This : access Typ) return MSSyst.Windows.Forms.ImageLayout.Valuetype;
   function get_BindingContext(
      This : access Typ) return MSSyst.Windows.Forms.BindingContext.Ref;
   function get_Bottom(
      This : access Typ) return Integer;
   function get_Bounds(
      This : access Typ) return MSSyst.Drawing.Rectangle.Valuetype;
   function get_CanFocus(
      This : access Typ) return Standard.Boolean;
   function get_CanSelect(
      This : access Typ) return Standard.Boolean;
   function get_Capture(
      This : access Typ) return Standard.Boolean;
   function get_CausesValidation(
      This : access Typ) return Standard.Boolean;
   function get_CheckForIllegalCrossThreadCalls return Standard.Boolean;
   function get_ClientRectangle(
      This : access Typ) return MSSyst.Drawing.Rectangle.Valuetype;
   function get_ClientSize(
      This : access Typ) return MSSyst.Drawing.Size.Valuetype;
   function get_CompanyName(
      This : access Typ) return MSSyst.String.Ref;
   function get_ContainsFocus(
      This : access Typ) return Standard.Boolean;
   function get_ContextMenu(
      This : access Typ) return MSSyst.Windows.Forms.ContextMenu.Ref;
   function get_ContextMenuStrip(
      This : access Typ) return MSSyst.Windows.Forms.ContextMenuStrip.Ref;
   function get_Controls(
      This : access Typ) return MSSyst.Windows.Forms.Control.ControlCollection.Ref;
   function get_Created(
      This : access Typ) return Standard.Boolean;
   function get_Cursor(
      This : access Typ) return MSSyst.Windows.Forms.Cursor.Ref;
   function get_DataBindings(
      This : access Typ) return MSSyst.Windows.Forms.ControlBindingsCollection.Ref;
   function get_DefaultBackColor return MSSyst.Drawing.Color.Valuetype;
   function get_DefaultFont return MSSyst.Drawing.Font.Ref;
   function get_DefaultForeColor return MSSyst.Drawing.Color.Valuetype;
   function get_DisplayRectangle(
      This : access Typ) return MSSyst.Drawing.Rectangle.Valuetype;
   function get_Disposing(
      This : access Typ) return Standard.Boolean;
   function get_Dock(
      This : access Typ) return MSSyst.Windows.Forms.DockStyle.Valuetype;
   function get_Enabled(
      This : access Typ) return Standard.Boolean;
   function get_Focused(
      This : access Typ) return Standard.Boolean;
   function get_Font(
      This : access Typ) return MSSyst.Drawing.Font.Ref;
   function get_ForeColor(
      This : access Typ) return MSSyst.Drawing.Color.Valuetype;
   function get_Handle(
      This : access Typ) return MSIL_Types.native_int;
   function get_HasChildren(
      This : access Typ) return Standard.Boolean;
   function get_Height(
      This : access Typ) return Integer;
   function get_ImeMode(
      This : access Typ) return MSSyst.Windows.Forms.ImeMode.Valuetype;
   function get_InvokeRequired(
      This : access Typ) return Standard.Boolean;
   function get_IsAccessible(
      This : access Typ) return Standard.Boolean;
   function get_IsDisposed(
      This : access Typ) return Standard.Boolean;
   function get_IsHandleCreated(
      This : access Typ) return Standard.Boolean;
   function get_IsMirrored(
      This : access Typ) return Standard.Boolean;
   function get_LayoutEngine(
      This : access Typ) return MSSyst.Windows.Forms.Layout.LayoutEngine.Ref;
   function get_Left(
      This : access Typ) return Integer;
   function get_Location(
      This : access Typ) return MSSyst.Drawing.Point.Valuetype;
   function get_Margin(
      This : access Typ) return MSSyst.Windows.Forms.Padding.Valuetype;
   function get_MaximumSize(
      This : access Typ) return MSSyst.Drawing.Size.Valuetype;
   function get_MinimumSize(
      This : access Typ) return MSSyst.Drawing.Size.Valuetype;
   function get_ModifierKeys return MSSyst.Windows.Forms.Keys.Valuetype;
   function get_MouseButtons return MSSyst.Windows.Forms.MouseButtons.Valuetype;
   function get_MousePosition return MSSyst.Drawing.Point.Valuetype;
   function get_Name(
      This : access Typ) return MSSyst.String.Ref;
   function get_Padding(
      This : access Typ) return MSSyst.Windows.Forms.Padding.Valuetype;
   function get_Parent(
      This : access Typ) return MSSyst.Windows.Forms.Control.Ref;
   function get_PreferredSize(
      This : access Typ) return MSSyst.Drawing.Size.Valuetype;
   function get_ProductName(
      This : access Typ) return MSSyst.String.Ref;
   function get_ProductVersion(
      This : access Typ) return MSSyst.String.Ref;
   function get_RecreatingHandle(
      This : access Typ) return Standard.Boolean;
   function get_Region(
      This : access Typ) return MSSyst.Drawing.Region.Ref;
   function get_Right(
      This : access Typ) return Integer;
   function get_RightToLeft(
      This : access Typ) return MSSyst.Windows.Forms.RightToLeft.Valuetype;
   function get_Site(
      This : access Typ) return MSSyst.ComponentModel.ISite.Ref;
   function get_Size(
      This : access Typ) return MSSyst.Drawing.Size.Valuetype;
   function get_TabIndex(
      This : access Typ) return Integer;
   function get_TabStop(
      This : access Typ) return Standard.Boolean;
   function get_Tag(
      This : access Typ) return MSSyst.Object.Ref;
   function get_Text(
      This : access Typ) return MSSyst.String.Ref;
   function get_Top(
      This : access Typ) return Integer;
   function get_TopLevelControl(
      This : access Typ) return MSSyst.Windows.Forms.Control.Ref;
   function get_UseWaitCursor(
      This : access Typ) return Standard.Boolean;
   function get_Visible(
      This : access Typ) return Standard.Boolean;
   function get_Width(
      This : access Typ) return Integer;
   function get_WindowTarget(
      This : access Typ) return MSSyst.Windows.Forms.IWindowTarget.Ref;
   function GetChildAtPoint(
      This : access Typ;
      pt : MSSyst.Drawing.Point.Valuetype;
      skipValue : MSSyst.Windows.Forms.GetChildAtPointSkip.Valuetype) return MSSyst.Windows.Forms.Control.Ref;
   function GetChildAtPoint(
      This : access Typ;
      pt : MSSyst.Drawing.Point.Valuetype) return MSSyst.Windows.Forms.Control.Ref;
   function GetContainerControl(
      This : access Typ) return MSSyst.Windows.Forms.IContainerControl.Ref;
   function GetNextControl(
      This : access Typ;
      ctl : MSSyst.Windows.Forms.Control.Ref;
      forward : Standard.Boolean) return MSSyst.Windows.Forms.Control.Ref;
   function GetPreferredSize(
      This : access Typ;
      proposedSize : MSSyst.Drawing.Size.Valuetype) return MSSyst.Drawing.Size.Valuetype;
   procedure Hide(
      This : access Typ);
   procedure Invalidate(
      This : access Typ;
      region : MSSyst.Drawing.Region.Ref;
      invalidateChildren : Standard.Boolean);
   procedure Invalidate(
      This : access Typ;
      rc : MSSyst.Drawing.Rectangle.Valuetype;
      invalidateChildren : Standard.Boolean);
   procedure Invalidate(
      This : access Typ;
      rc : MSSyst.Drawing.Rectangle.Valuetype);
   procedure Invalidate(
      This : access Typ;
      region : MSSyst.Drawing.Region.Ref);
   procedure Invalidate(
      This : access Typ;
      invalidateChildren : Standard.Boolean);
   procedure Invalidate(
      This : access Typ);
   function Invoke(
      This : access Typ;
      method : MSSyst.Delegate.Ref) return MSSyst.Object.Ref;
   function Invoke(
      This : access Typ;
      method : MSSyst.Delegate.Ref;
      args : MSSyst.Object.Ref_array) return MSSyst.Object.Ref;
   function IsKeyLocked(
      keyVal : MSSyst.Windows.Forms.Keys.Valuetype) return Standard.Boolean;
   function IsMnemonic(
      charCode : Wide_Character;
      text : MSSyst.String.Ref) return Standard.Boolean;
   procedure PerformLayout(
      This : access Typ;
      affectedControl : MSSyst.Windows.Forms.Control.Ref;
      affectedProperty : MSSyst.String.Ref);
   procedure PerformLayout(
      This : access Typ);
   function PointToClient(
      This : access Typ;
      p : MSSyst.Drawing.Point.Valuetype) return MSSyst.Drawing.Point.Valuetype;
   function PointToScreen(
      This : access Typ;
      p : MSSyst.Drawing.Point.Valuetype) return MSSyst.Drawing.Point.Valuetype;
   function PreProcessControlMessage(
      This : access Typ;
      msg : MSSyst.Windows.Forms.Message.Valuetype_addrof) return MSSyst.Windows.Forms.PreProcessControlState.Valuetype;
   function PreProcessMessage(
      This : access Typ;
      msg : MSSyst.Windows.Forms.Message.Valuetype_addrof) return Standard.Boolean;
   function RectangleToClient(
      This : access Typ;
      r : MSSyst.Drawing.Rectangle.Valuetype) return MSSyst.Drawing.Rectangle.Valuetype;
   function RectangleToScreen(
      This : access Typ;
      r : MSSyst.Drawing.Rectangle.Valuetype) return MSSyst.Drawing.Rectangle.Valuetype;
   procedure Refresh(
      This : access Typ);
   procedure remove_AutoSizeChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_BackColorChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_BackgroundImageChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_BackgroundImageLayoutChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_BindingContextChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_CausesValidationChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_ChangeUICues(
      This : access Typ;
      value : MSSyst.Windows.Forms.UICuesEventHandler.Ref);
   procedure remove_Click(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_ClientSizeChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_ContextMenuChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_ContextMenuStripChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_ControlAdded(
      This : access Typ;
      value : MSSyst.Windows.Forms.ControlEventHandler.Ref);
   procedure remove_ControlRemoved(
      This : access Typ;
      value : MSSyst.Windows.Forms.ControlEventHandler.Ref);
   procedure remove_CursorChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_DockChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_DoubleClick(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_DragDrop(
      This : access Typ;
      value : MSSyst.Windows.Forms.DragEventHandler.Ref);
   procedure remove_DragEnter(
      This : access Typ;
      value : MSSyst.Windows.Forms.DragEventHandler.Ref);
   procedure remove_DragLeave(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_DragOver(
      This : access Typ;
      value : MSSyst.Windows.Forms.DragEventHandler.Ref);
   procedure remove_EnabledChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_Enter(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_FontChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_ForeColorChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_GiveFeedback(
      This : access Typ;
      value : MSSyst.Windows.Forms.GiveFeedbackEventHandler.Ref);
   procedure remove_GotFocus(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_HandleCreated(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_HandleDestroyed(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_HelpRequested(
      This : access Typ;
      value : MSSyst.Windows.Forms.HelpEventHandler.Ref);
   procedure remove_ImeModeChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_Invalidated(
      This : access Typ;
      value : MSSyst.Windows.Forms.InvalidateEventHandler.Ref);
   procedure remove_KeyDown(
      This : access Typ;
      value : MSSyst.Windows.Forms.KeyEventHandler.Ref);
   procedure remove_KeyPress(
      This : access Typ;
      value : MSSyst.Windows.Forms.KeyPressEventHandler.Ref);
   procedure remove_KeyUp(
      This : access Typ;
      value : MSSyst.Windows.Forms.KeyEventHandler.Ref);
   procedure remove_Layout(
      This : access Typ;
      value : MSSyst.Windows.Forms.LayoutEventHandler.Ref);
   procedure remove_Leave(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_LocationChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_LostFocus(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_MarginChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_MouseCaptureChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_MouseClick(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure remove_MouseDoubleClick(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure remove_MouseDown(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure remove_MouseEnter(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_MouseHover(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_MouseLeave(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_MouseMove(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure remove_MouseUp(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure remove_MouseWheel(
      This : access Typ;
      value : MSSyst.Windows.Forms.MouseEventHandler.Ref);
   procedure remove_Move(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_PaddingChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_Paint(
      This : access Typ;
      value : MSSyst.Windows.Forms.PaintEventHandler.Ref);
   procedure remove_ParentChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_PreviewKeyDown(
      This : access Typ;
      value : MSSyst.Windows.Forms.PreviewKeyDownEventHandler.Ref);
   procedure remove_QueryAccessibilityHelp(
      This : access Typ;
      value : MSSyst.Windows.Forms.QueryAccessibilityHelpEventHandler.Ref);
   procedure remove_QueryContinueDrag(
      This : access Typ;
      value : MSSyst.Windows.Forms.QueryContinueDragEventHandler.Ref);
   procedure remove_RegionChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_Resize(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_RightToLeftChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_SizeChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_StyleChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_SystemColorsChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_TabIndexChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_TabStopChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_TextChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_Validated(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure remove_Validating(
      This : access Typ;
      value : MSSyst.ComponentModel.CancelEventHandler.Ref);
   procedure remove_VisibleChanged(
      This : access Typ;
      value : MSSyst.EventHandler.Ref);
   procedure ResetBackColor(
      This : access Typ);
   procedure ResetBindings(
      This : access Typ);
   procedure ResetCursor(
      This : access Typ);
   procedure ResetFont(
      This : access Typ);
   procedure ResetForeColor(
      This : access Typ);
   procedure ResetImeMode(
      This : access Typ);
   procedure ResetRightToLeft(
      This : access Typ);
   procedure ResetText(
      This : access Typ);
   procedure ResumeLayout(
      This : access Typ;
      performLayout : Standard.Boolean);
   procedure ResumeLayout(
      This : access Typ);
   procedure Scale(
      This : access Typ;
      ratio : Float);
   procedure Scale(
      This : access Typ;
      dx : Float;
      dy : Float);
   procedure Scale(
      This : access Typ;
      factor : MSSyst.Drawing.SizeF.Valuetype);
   procedure Select_k(
      This : access Typ);
   function SelectNextControl(
      This : access Typ;
      ctl : MSSyst.Windows.Forms.Control.Ref;
      forward : Standard.Boolean;
      tabStopOnly : Standard.Boolean;
      nested : Standard.Boolean;
      wrap : Standard.Boolean) return Standard.Boolean;
   procedure SendToBack(
      This : access Typ);
   procedure set_AccessibleDefaultActionDescription(
      This : access Typ;
      value : MSSyst.String.Ref);
   procedure set_AccessibleDescription(
      This : access Typ;
      value : MSSyst.String.Ref);
   procedure set_AccessibleName(
      This : access Typ;
      value : MSSyst.String.Ref);
   procedure set_AccessibleRole(
      This : access Typ;
      value : MSSyst.Windows.Forms.AccessibleRole.Valuetype);
   procedure set_AllowDrop(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_Anchor(
      This : access Typ;
      value : MSSyst.Windows.Forms.AnchorStyles.Valuetype);
   procedure set_AutoScrollOffset(
      This : access Typ;
      value : MSSyst.Drawing.Point.Valuetype);
   procedure set_AutoSize(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_BackColor(
      This : access Typ;
      value : MSSyst.Drawing.Color.Valuetype);
   procedure set_BackgroundImage(
      This : access Typ;
      value : MSSyst.Drawing.Image.Ref);
   procedure set_BackgroundImageLayout(
      This : access Typ;
      value : MSSyst.Windows.Forms.ImageLayout.Valuetype);
   procedure set_BindingContext(
      This : access Typ;
      value : MSSyst.Windows.Forms.BindingContext.Ref);
   procedure set_Bounds(
      This : access Typ;
      value : MSSyst.Drawing.Rectangle.Valuetype);
   procedure set_Capture(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_CausesValidation(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_CheckForIllegalCrossThreadCalls(
      value : Standard.Boolean);
   procedure set_ClientSize(
      This : access Typ;
      value : MSSyst.Drawing.Size.Valuetype);
   procedure set_ContextMenu(
      This : access Typ;
      value : MSSyst.Windows.Forms.ContextMenu.Ref);
   procedure set_ContextMenuStrip(
      This : access Typ;
      value : MSSyst.Windows.Forms.ContextMenuStrip.Ref);
   procedure set_Cursor(
      This : access Typ;
      value : MSSyst.Windows.Forms.Cursor.Ref);
   procedure set_Dock(
      This : access Typ;
      value : MSSyst.Windows.Forms.DockStyle.Valuetype);
   procedure set_Enabled(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_Font(
      This : access Typ;
      value : MSSyst.Drawing.Font.Ref);
   procedure set_ForeColor(
      This : access Typ;
      value : MSSyst.Drawing.Color.Valuetype);
   procedure set_Height(
      This : access Typ;
      value : Integer);
   procedure set_ImeMode(
      This : access Typ;
      value : MSSyst.Windows.Forms.ImeMode.Valuetype);
   procedure set_IsAccessible(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_Left(
      This : access Typ;
      value : Integer);
   procedure set_Location(
      This : access Typ;
      value : MSSyst.Drawing.Point.Valuetype);
   procedure set_Margin(
      This : access Typ;
      value : MSSyst.Windows.Forms.Padding.Valuetype);
   procedure set_MaximumSize(
      This : access Typ;
      value : MSSyst.Drawing.Size.Valuetype);
   procedure set_MinimumSize(
      This : access Typ;
      value : MSSyst.Drawing.Size.Valuetype);
   procedure set_Name(
      This : access Typ;
      value : MSSyst.String.Ref);
   procedure set_Padding(
      This : access Typ;
      value : MSSyst.Windows.Forms.Padding.Valuetype);
   procedure set_Parent(
      This : access Typ;
      value : MSSyst.Windows.Forms.Control.Ref);
   procedure set_Region(
      This : access Typ;
      value : MSSyst.Drawing.Region.Ref);
   procedure set_RightToLeft(
      This : access Typ;
      value : MSSyst.Windows.Forms.RightToLeft.Valuetype);
   procedure set_Site(
      This : access Typ;
      value : MSSyst.ComponentModel.ISite.Ref);
   procedure set_Size(
      This : access Typ;
      value : MSSyst.Drawing.Size.Valuetype);
   procedure set_TabIndex(
      This : access Typ;
      value : Integer);
   procedure set_TabStop(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_Tag(
      This : access Typ;
      value : MSSyst.Object.Ref);
   procedure set_Text(
      This : access Typ;
      value : MSSyst.String.Ref);
   procedure set_Top(
      This : access Typ;
      value : Integer);
   procedure set_UseWaitCursor(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_Visible(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_Width(
      This : access Typ;
      value : Integer);
   procedure set_WindowTarget(
      This : access Typ;
      value : MSSyst.Windows.Forms.IWindowTarget.Ref);
   procedure SetBounds(
      This : access Typ;
      x : Integer;
      y : Integer;
      width : Integer;
      height : Integer);
   procedure SetBounds(
      This : access Typ;
      x : Integer;
      y : Integer;
      width : Integer;
      height : Integer;
      specified : MSSyst.Windows.Forms.BoundsSpecified.Valuetype);
   procedure Show(
      This : access Typ);
   procedure SuspendLayout(
      This : access Typ);
   procedure Update(
      This : access Typ);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_Control);
   pragma Import(MSIL,add_AutoSizeChanged,"add_AutoSizeChanged");
   pragma Import(MSIL,add_BackColorChanged,"add_BackColorChanged");
   pragma Import(MSIL,add_BackgroundImageChanged,"add_BackgroundImageChanged");
   pragma Import(MSIL,add_BackgroundImageLayoutChanged,"add_BackgroundImageLayoutChanged");
   pragma Import(MSIL,add_BindingContextChanged,"add_BindingContextChanged");
   pragma Import(MSIL,add_CausesValidationChanged,"add_CausesValidationChanged");
   pragma Import(MSIL,add_ChangeUICues,"add_ChangeUICues");
   pragma Import(MSIL,add_Click,"add_Click");
   pragma Import(MSIL,add_ClientSizeChanged,"add_ClientSizeChanged");
   pragma Import(MSIL,add_ContextMenuChanged,"add_ContextMenuChanged");
   pragma Import(MSIL,add_ContextMenuStripChanged,"add_ContextMenuStripChanged");
   pragma Import(MSIL,add_ControlAdded,"add_ControlAdded");
   pragma Import(MSIL,add_ControlRemoved,"add_ControlRemoved");
   pragma Import(MSIL,add_CursorChanged,"add_CursorChanged");
   pragma Import(MSIL,add_DockChanged,"add_DockChanged");
   pragma Import(MSIL,add_DoubleClick,"add_DoubleClick");
   pragma Import(MSIL,add_DragDrop,"add_DragDrop");
   pragma Import(MSIL,add_DragEnter,"add_DragEnter");
   pragma Import(MSIL,add_DragLeave,"add_DragLeave");
   pragma Import(MSIL,add_DragOver,"add_DragOver");
   pragma Import(MSIL,add_EnabledChanged,"add_EnabledChanged");
   pragma Import(MSIL,add_Enter,"add_Enter");
   pragma Import(MSIL,add_FontChanged,"add_FontChanged");
   pragma Import(MSIL,add_ForeColorChanged,"add_ForeColorChanged");
   pragma Import(MSIL,add_GiveFeedback,"add_GiveFeedback");
   pragma Import(MSIL,add_GotFocus,"add_GotFocus");
   pragma Import(MSIL,add_HandleCreated,"add_HandleCreated");
   pragma Import(MSIL,add_HandleDestroyed,"add_HandleDestroyed");
   pragma Import(MSIL,add_HelpRequested,"add_HelpRequested");
   pragma Import(MSIL,add_ImeModeChanged,"add_ImeModeChanged");
   pragma Import(MSIL,add_Invalidated,"add_Invalidated");
   pragma Import(MSIL,add_KeyDown,"add_KeyDown");
   pragma Import(MSIL,add_KeyPress,"add_KeyPress");
   pragma Import(MSIL,add_KeyUp,"add_KeyUp");
   pragma Import(MSIL,add_Layout,"add_Layout");
   pragma Import(MSIL,add_Leave,"add_Leave");
   pragma Import(MSIL,add_LocationChanged,"add_LocationChanged");
   pragma Import(MSIL,add_LostFocus,"add_LostFocus");
   pragma Import(MSIL,add_MarginChanged,"add_MarginChanged");
   pragma Import(MSIL,add_MouseCaptureChanged,"add_MouseCaptureChanged");
   pragma Import(MSIL,add_MouseClick,"add_MouseClick");
   pragma Import(MSIL,add_MouseDoubleClick,"add_MouseDoubleClick");
   pragma Import(MSIL,add_MouseDown,"add_MouseDown");
   pragma Import(MSIL,add_MouseEnter,"add_MouseEnter");
   pragma Import(MSIL,add_MouseHover,"add_MouseHover");
   pragma Import(MSIL,add_MouseLeave,"add_MouseLeave");
   pragma Import(MSIL,add_MouseMove,"add_MouseMove");
   pragma Import(MSIL,add_MouseUp,"add_MouseUp");
   pragma Import(MSIL,add_MouseWheel,"add_MouseWheel");
   pragma Import(MSIL,add_Move,"add_Move");
   pragma Import(MSIL,add_PaddingChanged,"add_PaddingChanged");
   pragma Import(MSIL,add_Paint,"add_Paint");
   pragma Import(MSIL,add_ParentChanged,"add_ParentChanged");
   pragma Import(MSIL,add_PreviewKeyDown,"add_PreviewKeyDown");
   pragma Import(MSIL,add_QueryAccessibilityHelp,"add_QueryAccessibilityHelp");
   pragma Import(MSIL,add_QueryContinueDrag,"add_QueryContinueDrag");
   pragma Import(MSIL,add_RegionChanged,"add_RegionChanged");
   pragma Import(MSIL,add_Resize,"add_Resize");
   pragma Import(MSIL,add_RightToLeftChanged,"add_RightToLeftChanged");
   pragma Import(MSIL,add_SizeChanged,"add_SizeChanged");
   pragma Import(MSIL,add_StyleChanged,"add_StyleChanged");
   pragma Import(MSIL,add_SystemColorsChanged,"add_SystemColorsChanged");
   pragma Import(MSIL,add_TabIndexChanged,"add_TabIndexChanged");
   pragma Import(MSIL,add_TabStopChanged,"add_TabStopChanged");
   pragma Import(MSIL,add_TextChanged,"add_TextChanged");
   pragma Import(MSIL,add_Validated,"add_Validated");
   pragma Import(MSIL,add_Validating,"add_Validating");
   pragma Import(MSIL,add_VisibleChanged,"add_VisibleChanged");
   pragma Import(MSIL,BeginInvoke,"BeginInvoke");
   pragma Import(MSIL,BringToFront,"BringToFront");
   pragma Import(MSIL,Contains,"Contains");
   pragma Import(MSIL,CreateControl,"CreateControl");
   pragma Import(MSIL,CreateGraphics,"CreateGraphics");
   pragma Import(MSIL,DoDragDrop,"DoDragDrop");
   pragma Import(MSIL,DrawToBitmap,"DrawToBitmap");
   pragma Import(MSIL,EndInvoke,"EndInvoke");
   pragma Import(MSIL,FindForm,"FindForm");
   pragma Import(MSIL,Focus,"Focus");
   pragma Import(MSIL,FromChildHandle,"FromChildHandle");
   pragma Import(MSIL,FromHandle,"FromHandle");
   pragma Import(MSIL,get_AccessibilityObject,"get_AccessibilityObject");
   pragma Import(MSIL,get_AccessibleDefaultActionDescription,"get_AccessibleDefaultActionDescription");
   pragma Import(MSIL,get_AccessibleDescription,"get_AccessibleDescription");
   pragma Import(MSIL,get_AccessibleName,"get_AccessibleName");
   pragma Import(MSIL,get_AccessibleRole,"get_AccessibleRole");
   pragma Import(MSIL,get_AllowDrop,"get_AllowDrop");
   pragma Import(MSIL,get_Anchor,"get_Anchor");
   pragma Import(MSIL,get_AutoScrollOffset,"get_AutoScrollOffset");
   pragma Import(MSIL,get_AutoSize,"get_AutoSize");
   pragma Import(MSIL,get_BackColor,"get_BackColor");
   pragma Import(MSIL,get_BackgroundImage,"get_BackgroundImage");
   pragma Import(MSIL,get_BackgroundImageLayout,"get_BackgroundImageLayout");
   pragma Import(MSIL,get_BindingContext,"get_BindingContext");
   pragma Import(MSIL,get_Bottom,"get_Bottom");
   pragma Import(MSIL,get_Bounds,"get_Bounds");
   pragma Import(MSIL,get_CanFocus,"get_CanFocus");
   pragma Import(MSIL,get_CanSelect,"get_CanSelect");
   pragma Import(MSIL,get_Capture,"get_Capture");
   pragma Import(MSIL,get_CausesValidation,"get_CausesValidation");
   pragma Import(MSIL,get_CheckForIllegalCrossThreadCalls,"get_CheckForIllegalCrossThreadCalls");
   pragma Import(MSIL,get_ClientRectangle,"get_ClientRectangle");
   pragma Import(MSIL,get_ClientSize,"get_ClientSize");
   pragma Import(MSIL,get_CompanyName,"get_CompanyName");
   pragma Import(MSIL,get_ContainsFocus,"get_ContainsFocus");
   pragma Import(MSIL,get_ContextMenu,"get_ContextMenu");
   pragma Import(MSIL,get_ContextMenuStrip,"get_ContextMenuStrip");
   pragma Import(MSIL,get_Controls,"get_Controls");
   pragma Import(MSIL,get_Created,"get_Created");
   pragma Import(MSIL,get_Cursor,"get_Cursor");
   pragma Import(MSIL,get_DataBindings,"get_DataBindings");
   pragma Import(MSIL,get_DefaultBackColor,"get_DefaultBackColor");
   pragma Import(MSIL,get_DefaultFont,"get_DefaultFont");
   pragma Import(MSIL,get_DefaultForeColor,"get_DefaultForeColor");
   pragma Import(MSIL,get_DisplayRectangle,"get_DisplayRectangle");
   pragma Import(MSIL,get_Disposing,"get_Disposing");
   pragma Import(MSIL,get_Dock,"get_Dock");
   pragma Import(MSIL,get_Enabled,"get_Enabled");
   pragma Import(MSIL,get_Focused,"get_Focused");
   pragma Import(MSIL,get_Font,"get_Font");
   pragma Import(MSIL,get_ForeColor,"get_ForeColor");
   pragma Import(MSIL,get_Handle,"get_Handle");
   pragma Import(MSIL,get_HasChildren,"get_HasChildren");
   pragma Import(MSIL,get_Height,"get_Height");
   pragma Import(MSIL,get_ImeMode,"get_ImeMode");
   pragma Import(MSIL,get_InvokeRequired,"get_InvokeRequired");
   pragma Import(MSIL,get_IsAccessible,"get_IsAccessible");
   pragma Import(MSIL,get_IsDisposed,"get_IsDisposed");
   pragma Import(MSIL,get_IsHandleCreated,"get_IsHandleCreated");
   pragma Import(MSIL,get_IsMirrored,"get_IsMirrored");
   pragma Import(MSIL,get_LayoutEngine,"get_LayoutEngine");
   pragma Import(MSIL,get_Left,"get_Left");
   pragma Import(MSIL,get_Location,"get_Location");
   pragma Import(MSIL,get_Margin,"get_Margin");
   pragma Import(MSIL,get_MaximumSize,"get_MaximumSize");
   pragma Import(MSIL,get_MinimumSize,"get_MinimumSize");
   pragma Import(MSIL,get_ModifierKeys,"get_ModifierKeys");
   pragma Import(MSIL,get_MouseButtons,"get_MouseButtons");
   pragma Import(MSIL,get_MousePosition,"get_MousePosition");
   pragma Import(MSIL,get_Name,"get_Name");
   pragma Import(MSIL,get_Padding,"get_Padding");
   pragma Import(MSIL,get_Parent,"get_Parent");
   pragma Import(MSIL,get_PreferredSize,"get_PreferredSize");
   pragma Import(MSIL,get_ProductName,"get_ProductName");
   pragma Import(MSIL,get_ProductVersion,"get_ProductVersion");
   pragma Import(MSIL,get_RecreatingHandle,"get_RecreatingHandle");
   pragma Import(MSIL,get_Region,"get_Region");
   pragma Import(MSIL,get_Right,"get_Right");
   pragma Import(MSIL,get_RightToLeft,"get_RightToLeft");
   pragma Import(MSIL,get_Site,"get_Site");
   pragma Import(MSIL,get_Size,"get_Size");
   pragma Import(MSIL,get_TabIndex,"get_TabIndex");
   pragma Import(MSIL,get_TabStop,"get_TabStop");
   pragma Import(MSIL,get_Tag,"get_Tag");
   pragma Import(MSIL,get_Text,"get_Text");
   pragma Import(MSIL,get_Top,"get_Top");
   pragma Import(MSIL,get_TopLevelControl,"get_TopLevelControl");
   pragma Import(MSIL,get_UseWaitCursor,"get_UseWaitCursor");
   pragma Import(MSIL,get_Visible,"get_Visible");
   pragma Import(MSIL,get_Width,"get_Width");
   pragma Import(MSIL,get_WindowTarget,"get_WindowTarget");
   pragma Import(MSIL,GetChildAtPoint,"GetChildAtPoint");
   pragma Import(MSIL,GetContainerControl,"GetContainerControl");
   pragma Import(MSIL,GetNextControl,"GetNextControl");
   pragma Import(MSIL,GetPreferredSize,"GetPreferredSize");
   pragma Import(MSIL,Hide,"Hide");
   pragma Import(MSIL,Invalidate,"Invalidate");
   pragma Import(MSIL,Invoke,"Invoke");
   pragma Import(MSIL,IsKeyLocked,"IsKeyLocked");
   pragma Import(MSIL,IsMnemonic,"IsMnemonic");
   pragma Import(MSIL,PerformLayout,"PerformLayout");
   pragma Import(MSIL,PointToClient,"PointToClient");
   pragma Import(MSIL,PointToScreen,"PointToScreen");
   pragma Import(MSIL,PreProcessControlMessage,"PreProcessControlMessage");
   pragma Import(MSIL,PreProcessMessage,"PreProcessMessage");
   pragma Import(MSIL,RectangleToClient,"RectangleToClient");
   pragma Import(MSIL,RectangleToScreen,"RectangleToScreen");
   pragma Import(MSIL,Refresh,"Refresh");
   pragma Import(MSIL,remove_AutoSizeChanged,"remove_AutoSizeChanged");
   pragma Import(MSIL,remove_BackColorChanged,"remove_BackColorChanged");
   pragma Import(MSIL,remove_BackgroundImageChanged,"remove_BackgroundImageChanged");
   pragma Import(MSIL,remove_BackgroundImageLayoutChanged,"remove_BackgroundImageLayoutChanged");
   pragma Import(MSIL,remove_BindingContextChanged,"remove_BindingContextChanged");
   pragma Import(MSIL,remove_CausesValidationChanged,"remove_CausesValidationChanged");
   pragma Import(MSIL,remove_ChangeUICues,"remove_ChangeUICues");
   pragma Import(MSIL,remove_Click,"remove_Click");
   pragma Import(MSIL,remove_ClientSizeChanged,"remove_ClientSizeChanged");
   pragma Import(MSIL,remove_ContextMenuChanged,"remove_ContextMenuChanged");
   pragma Import(MSIL,remove_ContextMenuStripChanged,"remove_ContextMenuStripChanged");
   pragma Import(MSIL,remove_ControlAdded,"remove_ControlAdded");
   pragma Import(MSIL,remove_ControlRemoved,"remove_ControlRemoved");
   pragma Import(MSIL,remove_CursorChanged,"remove_CursorChanged");
   pragma Import(MSIL,remove_DockChanged,"remove_DockChanged");
   pragma Import(MSIL,remove_DoubleClick,"remove_DoubleClick");
   pragma Import(MSIL,remove_DragDrop,"remove_DragDrop");
   pragma Import(MSIL,remove_DragEnter,"remove_DragEnter");
   pragma Import(MSIL,remove_DragLeave,"remove_DragLeave");
   pragma Import(MSIL,remove_DragOver,"remove_DragOver");
   pragma Import(MSIL,remove_EnabledChanged,"remove_EnabledChanged");
   pragma Import(MSIL,remove_Enter,"remove_Enter");
   pragma Import(MSIL,remove_FontChanged,"remove_FontChanged");
   pragma Import(MSIL,remove_ForeColorChanged,"remove_ForeColorChanged");
   pragma Import(MSIL,remove_GiveFeedback,"remove_GiveFeedback");
   pragma Import(MSIL,remove_GotFocus,"remove_GotFocus");
   pragma Import(MSIL,remove_HandleCreated,"remove_HandleCreated");
   pragma Import(MSIL,remove_HandleDestroyed,"remove_HandleDestroyed");
   pragma Import(MSIL,remove_HelpRequested,"remove_HelpRequested");
   pragma Import(MSIL,remove_ImeModeChanged,"remove_ImeModeChanged");
   pragma Import(MSIL,remove_Invalidated,"remove_Invalidated");
   pragma Import(MSIL,remove_KeyDown,"remove_KeyDown");
   pragma Import(MSIL,remove_KeyPress,"remove_KeyPress");
   pragma Import(MSIL,remove_KeyUp,"remove_KeyUp");
   pragma Import(MSIL,remove_Layout,"remove_Layout");
   pragma Import(MSIL,remove_Leave,"remove_Leave");
   pragma Import(MSIL,remove_LocationChanged,"remove_LocationChanged");
   pragma Import(MSIL,remove_LostFocus,"remove_LostFocus");
   pragma Import(MSIL,remove_MarginChanged,"remove_MarginChanged");
   pragma Import(MSIL,remove_MouseCaptureChanged,"remove_MouseCaptureChanged");
   pragma Import(MSIL,remove_MouseClick,"remove_MouseClick");
   pragma Import(MSIL,remove_MouseDoubleClick,"remove_MouseDoubleClick");
   pragma Import(MSIL,remove_MouseDown,"remove_MouseDown");
   pragma Import(MSIL,remove_MouseEnter,"remove_MouseEnter");
   pragma Import(MSIL,remove_MouseHover,"remove_MouseHover");
   pragma Import(MSIL,remove_MouseLeave,"remove_MouseLeave");
   pragma Import(MSIL,remove_MouseMove,"remove_MouseMove");
   pragma Import(MSIL,remove_MouseUp,"remove_MouseUp");
   pragma Import(MSIL,remove_MouseWheel,"remove_MouseWheel");
   pragma Import(MSIL,remove_Move,"remove_Move");
   pragma Import(MSIL,remove_PaddingChanged,"remove_PaddingChanged");
   pragma Import(MSIL,remove_Paint,"remove_Paint");
   pragma Import(MSIL,remove_ParentChanged,"remove_ParentChanged");
   pragma Import(MSIL,remove_PreviewKeyDown,"remove_PreviewKeyDown");
   pragma Import(MSIL,remove_QueryAccessibilityHelp,"remove_QueryAccessibilityHelp");
   pragma Import(MSIL,remove_QueryContinueDrag,"remove_QueryContinueDrag");
   pragma Import(MSIL,remove_RegionChanged,"remove_RegionChanged");
   pragma Import(MSIL,remove_Resize,"remove_Resize");
   pragma Import(MSIL,remove_RightToLeftChanged,"remove_RightToLeftChanged");
   pragma Import(MSIL,remove_SizeChanged,"remove_SizeChanged");
   pragma Import(MSIL,remove_StyleChanged,"remove_StyleChanged");
   pragma Import(MSIL,remove_SystemColorsChanged,"remove_SystemColorsChanged");
   pragma Import(MSIL,remove_TabIndexChanged,"remove_TabIndexChanged");
   pragma Import(MSIL,remove_TabStopChanged,"remove_TabStopChanged");
   pragma Import(MSIL,remove_TextChanged,"remove_TextChanged");
   pragma Import(MSIL,remove_Validated,"remove_Validated");
   pragma Import(MSIL,remove_Validating,"remove_Validating");
   pragma Import(MSIL,remove_VisibleChanged,"remove_VisibleChanged");
   pragma Import(MSIL,ResetBackColor,"ResetBackColor");
   pragma Import(MSIL,ResetBindings,"ResetBindings");
   pragma Import(MSIL,ResetCursor,"ResetCursor");
   pragma Import(MSIL,ResetFont,"ResetFont");
   pragma Import(MSIL,ResetForeColor,"ResetForeColor");
   pragma Import(MSIL,ResetImeMode,"ResetImeMode");
   pragma Import(MSIL,ResetRightToLeft,"ResetRightToLeft");
   pragma Import(MSIL,ResetText,"ResetText");
   pragma Import(MSIL,ResumeLayout,"ResumeLayout");
   pragma Import(MSIL,Scale,"Scale");
   pragma Import(MSIL,Select_k,"Select");
   pragma Import(MSIL,SelectNextControl,"SelectNextControl");
   pragma Import(MSIL,SendToBack,"SendToBack");
   pragma Import(MSIL,set_AccessibleDefaultActionDescription,"set_AccessibleDefaultActionDescription");
   pragma Import(MSIL,set_AccessibleDescription,"set_AccessibleDescription");
   pragma Import(MSIL,set_AccessibleName,"set_AccessibleName");
   pragma Import(MSIL,set_AccessibleRole,"set_AccessibleRole");
   pragma Import(MSIL,set_AllowDrop,"set_AllowDrop");
   pragma Import(MSIL,set_Anchor,"set_Anchor");
   pragma Import(MSIL,set_AutoScrollOffset,"set_AutoScrollOffset");
   pragma Import(MSIL,set_AutoSize,"set_AutoSize");
   pragma Import(MSIL,set_BackColor,"set_BackColor");
   pragma Import(MSIL,set_BackgroundImage,"set_BackgroundImage");
   pragma Import(MSIL,set_BackgroundImageLayout,"set_BackgroundImageLayout");
   pragma Import(MSIL,set_BindingContext,"set_BindingContext");
   pragma Import(MSIL,set_Bounds,"set_Bounds");
   pragma Import(MSIL,set_Capture,"set_Capture");
   pragma Import(MSIL,set_CausesValidation,"set_CausesValidation");
   pragma Import(MSIL,set_CheckForIllegalCrossThreadCalls,"set_CheckForIllegalCrossThreadCalls");
   pragma Import(MSIL,set_ClientSize,"set_ClientSize");
   pragma Import(MSIL,set_ContextMenu,"set_ContextMenu");
   pragma Import(MSIL,set_ContextMenuStrip,"set_ContextMenuStrip");
   pragma Import(MSIL,set_Cursor,"set_Cursor");
   pragma Import(MSIL,set_Dock,"set_Dock");
   pragma Import(MSIL,set_Enabled,"set_Enabled");
   pragma Import(MSIL,set_Font,"set_Font");
   pragma Import(MSIL,set_ForeColor,"set_ForeColor");
   pragma Import(MSIL,set_Height,"set_Height");
   pragma Import(MSIL,set_ImeMode,"set_ImeMode");
   pragma Import(MSIL,set_IsAccessible,"set_IsAccessible");
   pragma Import(MSIL,set_Left,"set_Left");
   pragma Import(MSIL,set_Location,"set_Location");
   pragma Import(MSIL,set_Margin,"set_Margin");
   pragma Import(MSIL,set_MaximumSize,"set_MaximumSize");
   pragma Import(MSIL,set_MinimumSize,"set_MinimumSize");
   pragma Import(MSIL,set_Name,"set_Name");
   pragma Import(MSIL,set_Padding,"set_Padding");
   pragma Import(MSIL,set_Parent,"set_Parent");
   pragma Import(MSIL,set_Region,"set_Region");
   pragma Import(MSIL,set_RightToLeft,"set_RightToLeft");
   pragma Import(MSIL,set_Site,"set_Site");
   pragma Import(MSIL,set_Size,"set_Size");
   pragma Import(MSIL,set_TabIndex,"set_TabIndex");
   pragma Import(MSIL,set_TabStop,"set_TabStop");
   pragma Import(MSIL,set_Tag,"set_Tag");
   pragma Import(MSIL,set_Text,"set_Text");
   pragma Import(MSIL,set_Top,"set_Top");
   pragma Import(MSIL,set_UseWaitCursor,"set_UseWaitCursor");
   pragma Import(MSIL,set_Visible,"set_Visible");
   pragma Import(MSIL,set_Width,"set_Width");
   pragma Import(MSIL,set_WindowTarget,"set_WindowTarget");
   pragma Import(MSIL,SetBounds,"SetBounds");
   pragma Import(MSIL,Show,"Show");
   pragma Import(MSIL,SuspendLayout,"SuspendLayout");
   pragma Import(MSIL,Update,"Update");
end MSSyst.Windows.Forms.Control;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Windows.Forms.Control,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.Control");
