-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Drawing.Printing.PrintController;
with type MSSyst.Object.Ref is access;
with type MSSyst.Drawing.Printing.PreviewPageInfo.Ref_array is access;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.Drawing.Printing.PrintDocument.Ref is access;
with type MSSyst.Drawing.Printing.PrintPageEventArgs.Ref is access;
with type MSSyst.Drawing.Printing.PrintEventArgs.Ref is access;
with type MSSyst.Drawing.Graphics.Ref is access;
with type MSSyst.String.Ref is access;
package MSSyst.Drawing.Printing.PreviewPrintController is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.Drawing.Printing.PrintController.Typ   with record
      null;
   end record;
   function new_PreviewPrintController(
      This : Ref := null) return Ref;
   function get_IsPreview(
      This : access Typ) return Standard.Boolean;
   function get_UseAntiAlias(
      This : access Typ) return Standard.Boolean;
   function GetPreviewPageInfo(
      This : access Typ) return MSSyst.Drawing.Printing.PreviewPageInfo.Ref_array;
   procedure OnEndPage(
      This : access Typ;
      document : MSSyst.Drawing.Printing.PrintDocument.Ref;
      e : MSSyst.Drawing.Printing.PrintPageEventArgs.Ref);
   procedure OnEndPrint(
      This : access Typ;
      document : MSSyst.Drawing.Printing.PrintDocument.Ref;
      e : MSSyst.Drawing.Printing.PrintEventArgs.Ref);
   function OnStartPage(
      This : access Typ;
      document : MSSyst.Drawing.Printing.PrintDocument.Ref;
      e : MSSyst.Drawing.Printing.PrintPageEventArgs.Ref) return MSSyst.Drawing.Graphics.Ref;
   procedure OnStartPrint(
      This : access Typ;
      document : MSSyst.Drawing.Printing.PrintDocument.Ref;
      e : MSSyst.Drawing.Printing.PrintEventArgs.Ref);
   procedure set_UseAntiAlias(
      This : access Typ;
      value : Standard.Boolean);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_PreviewPrintController);
   pragma Import(MSIL,get_IsPreview,"get_IsPreview");
   pragma Import(MSIL,get_UseAntiAlias,"get_UseAntiAlias");
   pragma Import(MSIL,GetPreviewPageInfo,"GetPreviewPageInfo");
   pragma Import(MSIL,OnEndPage,"OnEndPage");
   pragma Import(MSIL,OnEndPrint,"OnEndPrint");
   pragma Import(MSIL,OnStartPage,"OnStartPage");
   pragma Import(MSIL,OnStartPrint,"OnStartPrint");
   pragma Import(MSIL,set_UseAntiAlias,"set_UseAntiAlias");
end MSSyst.Drawing.Printing.PreviewPrintController;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Drawing.Printing.PreviewPrintController,
   ".ver 2:0:0:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[System.Drawing]System.Drawing.Printing.PreviewPrintController");
