-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
package MSSyst.Diagnostics.SymbolStore is
end MSSyst.Diagnostics.SymbolStore;
