-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Object;
with type MSSyst.ActivationContext.Ref is access;
with type MSSyst.Security.Policy.TrustManagerContext.Ref is access;
with type MSSyst.Security.Policy.IApplicationTrustManager.Ref is access;
with type MSSyst.Security.Policy.ApplicationTrustCollection.Ref is access;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.String.Ref is access;
package MSSyst.Security.Policy.ApplicationSecurityManager is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is abstract new MSSyst.Object.Typ   with record
      null;
   end record;
   function DetermineApplicationTrust(
      activationContext : MSSyst.ActivationContext.Ref;
      context : MSSyst.Security.Policy.TrustManagerContext.Ref) return Standard.Boolean;
   function get_ApplicationTrustManager return MSSyst.Security.Policy.IApplicationTrustManager.Ref;
   function get_UserApplicationTrusts return MSSyst.Security.Policy.ApplicationTrustCollection.Ref;
private
   pragma Convention(MSIL,Typ);
   pragma Import(MSIL,DetermineApplicationTrust,"DetermineApplicationTrust");
   pragma Import(MSIL,get_ApplicationTrustManager,"get_ApplicationTrustManager");
   pragma Import(MSIL,get_UserApplicationTrusts,"get_UserApplicationTrusts");
end MSSyst.Security.Policy.ApplicationSecurityManager;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Security.Policy.ApplicationSecurityManager,
   ".ver 2.0.0.0 .publickeytoken=( 96 9d b8 05 3d 33 22 ac )",
   "[mscorlib]System.Security.Policy.ApplicationSecurityManager");
