-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Security.AccessControl.KnownAce;
with type MSSyst.Security.AccessControl.GenericAce.Ref is access;
with type MSSyst.Object.Ref is access;
with MSSyst.Security.AccessControl.AceFlags;
with MSSyst.Security.AccessControl.AceType;
with MSSyst.Security.AccessControl.AuditFlags;
with MSSyst.Security.AccessControl.CompoundAceType;
with MSSyst.Security.AccessControl.InheritanceFlags;
with MSSyst.Security.AccessControl.PropagationFlags;
with type MSSyst.Security.Principal.SecurityIdentifier.Ref is access;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.String.Ref is access;
package MSSyst.Security.AccessControl.CompoundAce is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.Security.AccessControl.KnownAce.Typ   with record
      null;
   end record;
   function new_CompoundAce(
      This : Ref := null;
      flags : MSSyst.Security.AccessControl.AceFlags.Valuetype;
      accessMask : Integer;
      compoundAceType : MSSyst.Security.AccessControl.CompoundAceType.Valuetype;
      sid : MSSyst.Security.Principal.SecurityIdentifier.Ref) return Ref;
   function get_BinaryLength(
      This : access Typ) return Integer;
   function get_CompoundAceType(
      This : access Typ) return MSSyst.Security.AccessControl.CompoundAceType.Valuetype;
   procedure GetBinaryForm(
      This : access Typ;
      binaryForm : MSIL_Types.unsigned_int8_Arr;
      offset : Integer);
   procedure set_CompoundAceType(
      This : access Typ;
      value : MSSyst.Security.AccessControl.CompoundAceType.Valuetype);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_CompoundAce);
   pragma Import(MSIL,get_BinaryLength,"get_BinaryLength");
   pragma Import(MSIL,get_CompoundAceType,"get_CompoundAceType");
   pragma Import(MSIL,GetBinaryForm,"GetBinaryForm");
   pragma Import(MSIL,set_CompoundAceType,"set_CompoundAceType");
end MSSyst.Security.AccessControl.CompoundAce;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Security.AccessControl.CompoundAce,
   ".ver 2.0.0.0 .publickeytoken=( 96 9d b8 05 3d 33 22 ac )",
   "[mscorlib]System.Security.AccessControl.CompoundAce");
