-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with type MSSyst.Runtime.Remoting.Contexts.Context.Ref is access;
with type MSSyst.String.Ref is access;
package MSSyst.Runtime.Remoting.Contexts.IContextProperty is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is interface;
   procedure Freeze(
      This : access Typ;
      newContext : MSSyst.Runtime.Remoting.Contexts.Context.Ref) is abstract;
   function get_Name(
      This : access Typ) return MSSyst.String.Ref is abstract;
   function IsNewContextOK(
      This : access Typ;
      newCtx : MSSyst.Runtime.Remoting.Contexts.Context.Ref) return Standard.Boolean is abstract;
private
   pragma Import(MSIL,Freeze,"Freeze");
   pragma Import(MSIL,get_Name,"get_Name");
   pragma Import(MSIL,IsNewContextOK,"IsNewContextOK");
end MSSyst.Runtime.Remoting.Contexts.IContextProperty;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Runtime.Remoting.Contexts.IContextProperty,
   ".ver 2.0.0.0 .publickeytoken=( 96 9d b8 05 3d 33 22 ac )",
   "[mscorlib]System.Runtime.Remoting.Contexts.IContextProperty");
