-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with type MSSyst.ComponentModel.AttributeCollection.Ref is access;
with type MSSyst.Object.Ref is access;
with type MSSyst.String.Ref is access;
with type MSSyst.ComponentModel.TypeConverter.Ref is access;
with type MSSyst.ComponentModel.EventDescriptor.Ref is access;
with type MSSyst.ComponentModel.PropertyDescriptor.Ref is access;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.ComponentModel.EventDescriptorCollection.Ref is access;
with type MSSyst.Attribute.Ref_array is access;
with type MSSyst.ComponentModel.PropertyDescriptorCollection.Ref is access;
package MSSyst.ComponentModel.IComNativeDescriptorHandler is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is interface;
   function GetAttributes(
      This : access Typ;
      component : MSSyst.Object.Ref) return MSSyst.ComponentModel.AttributeCollection.Ref is abstract;
   function GetClassName(
      This : access Typ;
      component : MSSyst.Object.Ref) return MSSyst.String.Ref is abstract;
   function GetConverter(
      This : access Typ;
      component : MSSyst.Object.Ref) return MSSyst.ComponentModel.TypeConverter.Ref is abstract;
   function GetDefaultEvent(
      This : access Typ;
      component : MSSyst.Object.Ref) return MSSyst.ComponentModel.EventDescriptor.Ref is abstract;
   function GetDefaultProperty(
      This : access Typ;
      component : MSSyst.Object.Ref) return MSSyst.ComponentModel.PropertyDescriptor.Ref is abstract;
   function GetEditor(
      This : access Typ;
      component : MSSyst.Object.Ref;
      baseEditorType : MSSyst.Type_k.Ref) return MSSyst.Object.Ref is abstract;
   function GetEvents(
      This : access Typ;
      component : MSSyst.Object.Ref;
      attributes : MSSyst.Attribute.Ref_array) return MSSyst.ComponentModel.EventDescriptorCollection.Ref is abstract;
   function GetEvents(
      This : access Typ;
      component : MSSyst.Object.Ref) return MSSyst.ComponentModel.EventDescriptorCollection.Ref is abstract;
   function GetName(
      This : access Typ;
      component : MSSyst.Object.Ref) return MSSyst.String.Ref is abstract;
   function GetProperties(
      This : access Typ;
      component : MSSyst.Object.Ref;
      attributes : MSSyst.Attribute.Ref_array) return MSSyst.ComponentModel.PropertyDescriptorCollection.Ref is abstract;
   function GetPropertyValue(
      This : access Typ;
      component : MSSyst.Object.Ref;
      dispid : Integer;
      success : MSIL_Types.Bool_addrof) return MSSyst.Object.Ref is abstract;
   function GetPropertyValue(
      This : access Typ;
      component : MSSyst.Object.Ref;
      propertyName : MSSyst.String.Ref;
      success : MSIL_Types.Bool_addrof) return MSSyst.Object.Ref is abstract;
private
   pragma Import(MSIL,GetAttributes,"GetAttributes");
   pragma Import(MSIL,GetClassName,"GetClassName");
   pragma Import(MSIL,GetConverter,"GetConverter");
   pragma Import(MSIL,GetDefaultEvent,"GetDefaultEvent");
   pragma Import(MSIL,GetDefaultProperty,"GetDefaultProperty");
   pragma Import(MSIL,GetEditor,"GetEditor");
   pragma Import(MSIL,GetEvents,"GetEvents");
   pragma Import(MSIL,GetName,"GetName");
   pragma Import(MSIL,GetProperties,"GetProperties");
   pragma Import(MSIL,GetPropertyValue,"GetPropertyValue");
end MSSyst.ComponentModel.IComNativeDescriptorHandler;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.ComponentModel.IComNativeDescriptorHandler,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System]System.ComponentModel.IComNativeDescriptorHandler");
