-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Object;
with type MSSyst.Security.Principal.IdentityReference.Ref is access;
with MSSyst.Security.AccessControl.InheritanceFlags;
with MSSyst.Security.AccessControl.PropagationFlags;
with type MSSyst.Type_k.Ref is access;
with type MSSyst.String.Ref is access;
package MSSyst.Security.AccessControl.AuthorizationRule is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is abstract new MSSyst.Object.Typ   with record
      null;
   end record;
   function get_IdentityReference(
      This : access Typ) return MSSyst.Security.Principal.IdentityReference.Ref;
   function get_InheritanceFlags(
      This : access Typ) return MSSyst.Security.AccessControl.InheritanceFlags.Valuetype;
   function get_IsInherited(
      This : access Typ) return Standard.Boolean;
   function get_PropagationFlags(
      This : access Typ) return MSSyst.Security.AccessControl.PropagationFlags.Valuetype;
private
   pragma Convention(MSIL,Typ);
   pragma Import(MSIL,get_IdentityReference,"get_IdentityReference");
   pragma Import(MSIL,get_InheritanceFlags,"get_InheritanceFlags");
   pragma Import(MSIL,get_IsInherited,"get_IsInherited");
   pragma Import(MSIL,get_PropagationFlags,"get_PropagationFlags");
end MSSyst.Security.AccessControl.AuthorizationRule;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Security.AccessControl.AuthorizationRule,
   ".ver 2.0.0.0 .publickeytoken=( 96 9d b8 05 3d 33 22 ac )",
   "[mscorlib]System.Security.AccessControl.AuthorizationRule");
