-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.CodeDom.CodeTypeDeclaration;
with type MSSyst.EventHandler.Ref is access;
with type MSSyst.Object.Ref is access;
with MSSyst.CodeDom.MemberAttributes;
with type MSSyst.CodeDom.CodeTypeReferenceCollection.Ref is access;
with type MSSyst.CodeDom.CodeCommentStatementCollection.Ref is access;
with type MSSyst.CodeDom.CodeAttributeDeclarationCollection.Ref is access;
with type MSSyst.CodeDom.CodeDirectiveCollection.Ref is access;
with type MSSyst.CodeDom.CodeLinePragma.Ref is access;
with type MSSyst.CodeDom.CodeTypeMemberCollection.Ref is access;
with type MSSyst.String.Ref is access;
with type MSSyst.CodeDom.CodeParameterDeclarationExpressionCollection.Ref is access;
with type MSSyst.CodeDom.CodeTypeReference.Ref is access;
with MSSyst.Reflection.TypeAttributes;
with type MSSyst.CodeDom.CodeTypeParameterCollection.Ref is access;
with type MSSyst.Collections.IDictionary.Ref is access;
with type MSSyst.Type_k.Ref is access;
package MSSyst.CodeDom.CodeTypeDelegate is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.CodeDom.CodeTypeDeclaration.Typ   with record
      null;
   end record;
   function new_CodeTypeDelegate(
      This : Ref := null) return Ref;
   function new_CodeTypeDelegate(
      This : Ref := null;
      name : MSSyst.String.Ref) return Ref;
   function get_Parameters(
      This : access Typ) return MSSyst.CodeDom.CodeParameterDeclarationExpressionCollection.Ref;
   function get_ReturnType(
      This : access Typ) return MSSyst.CodeDom.CodeTypeReference.Ref;
   procedure set_ReturnType(
      This : access Typ;
      value : MSSyst.CodeDom.CodeTypeReference.Ref);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_CodeTypeDelegate);
   pragma Import(MSIL,get_Parameters,"get_Parameters");
   pragma Import(MSIL,get_ReturnType,"get_ReturnType");
   pragma Import(MSIL,set_ReturnType,"set_ReturnType");
end MSSyst.CodeDom.CodeTypeDelegate;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.CodeDom.CodeTypeDelegate,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System]System.CodeDom.CodeTypeDelegate");
