-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with type MSSyst.Object.Ref is access;
with type MSSyst.Type_k.Ref is access;
with MSSyst.TypeCode;
with type MSSyst.String.Ref is access;
with type MSSyst.IFormatProvider.Ref is access;
package MSSyst.Windows.Forms.VisualStyles.ScrollBarArrowButtonState is
   type ValueType is (
      UpNormal,
      UpHot,
      UpPressed,
      UpDisabled,
      DownNormal,
      DownHot,
      DownPressed,
      DownDisabled,
      LeftNormal,
      LeftHot,
      LeftPressed,
      LeftDisabled,
      RightNormal,
      RightHot,
      RightPressed,
      RightDisabled);
   pragma Convention (MSIL, ValueType);
   for ValueType use (
      UpNormal =>  0,
      UpHot =>  2,
      UpPressed =>  3,
      UpDisabled =>  4,
      DownNormal =>  5,
      DownHot =>  6,
      DownPressed =>  7,
      DownDisabled =>  8,
      LeftNormal =>  9,
      LeftHot =>  10,
      LeftPressed =>  11,
      LeftDisabled =>  12,
      RightNormal =>  13,
      RightHot =>  14,
      RightPressed =>  15,
      RightDisabled =>  16);
   type ValueType_Arr is array (Natural range <>) of ValueType; -- start at 0
   type ValueType_Array is access all ValueType_Arr;
   type ValueType_addrof is access all ValueType;
   type ValueType_array_addrof is access all ValueType_Array;
   function CompareTo(
      This : Valuetype;
      target : MSSyst.Object.Ref) return Integer;
   function Equals(
      This : Valuetype;
      obj : MSSyst.Object.Ref) return Standard.Boolean;
   function GetHashCode(
      This : Valuetype) return Integer;
   function GetType(
      This : Valuetype) return MSSyst.Type_k.Ref;
   function GetTypeCode(
      This : Valuetype) return MSSyst.TypeCode.Valuetype;
   function ToString(
      This : Valuetype;
      provider : MSSyst.IFormatProvider.Ref) return MSSyst.String.Ref;
   function ToString(
      This : Valuetype) return MSSyst.String.Ref;
   function ToString(
      This : Valuetype;
      format : MSSyst.String.Ref;
      provider : MSSyst.IFormatProvider.Ref) return MSSyst.String.Ref;
   function ToString(
      This : Valuetype;
      format : MSSyst.String.Ref) return MSSyst.String.Ref;
private
   pragma Import(MSIL,CompareTo,"CompareTo");
   pragma Import(MSIL,Equals,"Equals");
   pragma Import(MSIL,GetHashCode,"GetHashCode");
   pragma Import(MSIL,GetType,"GetType");
   pragma Import(MSIL,GetTypeCode,"GetTypeCode");
   pragma Import(MSIL,ToString,"ToString");
end MSSyst.Windows.Forms.VisualStyles.ScrollBarArrowButtonState;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Windows.Forms.VisualStyles.ScrollBarArrowButtonState,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.VisualStyles.ScrollBarArrowButtonState");
