-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
pragma Extensions_Allowed(On);
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Object;
with type MSSyst.Windows.Forms.Control.Ref is access;
with type MSSyst.Drawing.Point.Valuetype is tagged;
with type MSSyst.Drawing.Rectangle.Valuetype is tagged;
with type MSSyst.Windows.Forms.Screen.Ref_array is access;
with type MSSyst.String.Ref is access;
with type MSSyst.Type_k.Ref is access;
package MSSyst.Windows.Forms.Screen is
   type Typ;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   type Typ is new MSSyst.Object.Typ   with record
      null;
   end record;
   function Equals(
      This : access Typ;
      obj : MSSyst.Object.Ref) return Standard.Boolean;
   function FromControl(
      control : MSSyst.Windows.Forms.Control.Ref) return MSSyst.Windows.Forms.Screen.Ref;
   function FromHandle(
      hwnd : MSIL_Types.native_int) return MSSyst.Windows.Forms.Screen.Ref;
   function FromPoint(
      point : MSSyst.Drawing.Point.Valuetype) return MSSyst.Windows.Forms.Screen.Ref;
   function FromRectangle(
      rect : MSSyst.Drawing.Rectangle.Valuetype) return MSSyst.Windows.Forms.Screen.Ref;
   function get_AllScreens return MSSyst.Windows.Forms.Screen.Ref_array;
   function get_BitsPerPixel(
      This : access Typ) return Integer;
   function get_Bounds(
      This : access Typ) return MSSyst.Drawing.Rectangle.Valuetype;
   function get_DeviceName(
      This : access Typ) return MSSyst.String.Ref;
   function get_Primary(
      This : access Typ) return Standard.Boolean;
   function get_PrimaryScreen return MSSyst.Windows.Forms.Screen.Ref;
   function get_WorkingArea(
      This : access Typ) return MSSyst.Drawing.Rectangle.Valuetype;
   function GetBounds(
      ctl : MSSyst.Windows.Forms.Control.Ref) return MSSyst.Drawing.Rectangle.Valuetype;
   function GetBounds(
      pt : MSSyst.Drawing.Point.Valuetype) return MSSyst.Drawing.Rectangle.Valuetype;
   function GetBounds(
      rect : MSSyst.Drawing.Rectangle.Valuetype) return MSSyst.Drawing.Rectangle.Valuetype;
   function GetHashCode(
      This : access Typ) return Integer;
   function GetWorkingArea(
      pt : MSSyst.Drawing.Point.Valuetype) return MSSyst.Drawing.Rectangle.Valuetype;
   function GetWorkingArea(
      rect : MSSyst.Drawing.Rectangle.Valuetype) return MSSyst.Drawing.Rectangle.Valuetype;
   function GetWorkingArea(
      ctl : MSSyst.Windows.Forms.Control.Ref) return MSSyst.Drawing.Rectangle.Valuetype;
   function ToString(
      This : access Typ) return MSSyst.String.Ref;
private
   pragma Convention(MSIL,Typ);
   pragma Import(MSIL,Equals,"Equals");
   pragma Import(MSIL,FromControl,"FromControl");
   pragma Import(MSIL,FromHandle,"FromHandle");
   pragma Import(MSIL,FromPoint,"FromPoint");
   pragma Import(MSIL,FromRectangle,"FromRectangle");
   pragma Import(MSIL,get_AllScreens,"get_AllScreens");
   pragma Import(MSIL,get_BitsPerPixel,"get_BitsPerPixel");
   pragma Import(MSIL,get_Bounds,"get_Bounds");
   pragma Import(MSIL,get_DeviceName,"get_DeviceName");
   pragma Import(MSIL,get_Primary,"get_Primary");
   pragma Import(MSIL,get_PrimaryScreen,"get_PrimaryScreen");
   pragma Import(MSIL,get_WorkingArea,"get_WorkingArea");
   pragma Import(MSIL,GetBounds,"GetBounds");
   pragma Import(MSIL,GetHashCode,"GetHashCode");
   pragma Import(MSIL,GetWorkingArea,"GetWorkingArea");
   pragma Import(MSIL,ToString,"ToString");
end MSSyst.Windows.Forms.Screen;
pragma Extensions_Allowed(Off);
pragma Import(MSIL,MSSyst.Windows.Forms.Screen,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.Screen");
