@echo -------------------- BUILDING --------------------

mgnatmake array_range.adb
mgnatmake bug20030120a.adb
mgnatmake bug20030120b.adb
mgnatmake bug20030121a.adb
mgnatmake bug20050830.adb
mgnatmake bug20050909a.adb
mgnatmake echo_args.adb
mgnatmake float_test.adb
mgnatmake fred.adb
mgnatmake hello.adb
mgnatmake hello_ada.adb
mgnatmake hello_file.adb
mgnatmake seq_io.adb
mgnatmake test_array_bounds.adb
mgnatmake test_assembly.adb
mgnatmake test_assign.adb
mgnatmake test_assign2.adb
mgnatmake test_atc.adb
mgnatmake test_attributes.adb
mgnatmake test_bool_addrof.adb
mgnatmake test_byte_array.adb
mgnatmake test_calendar.adb
mgnatmake test_case.adb
mgnatmake test_case2.adb
mgnatmake test_case3.adb
mgnatmake testcase2.adb
mgnatmake testcase3.adb
mgnatmake test_composite.adb
mgnatmake test_controlled.adb
mgnatmake test_controlled_pkg.adb
mgnatmake test_device_error.adb
mgnatmake test_direct_io.adb
mgnatmake test_enum_attrib.adb
mgnatmake test_enum_get.adb
mgnatmake test_environment.adb
mgnatmake test_eof.adb
mgnatmake test_exception.adb
mgnatmake test_exports_main.adb
mgnatmake test_file.adb
mgnatmake test_file2.adb
mgnatmake test_finalize.adb
mgnatmake test_fix_io.adb
mgnatmake test_gen.adb
mgnatmake test_generic_enum_main.adb
mgnatmake test_handling.adb
mgnatmake test_interface.adb
mgnatmake test_interfaces.adb
mgnatmake test_long_float.adb
mgnatmake test_loop.adb
mgnatmake test_lower.adb
mgnatmake test_main.adb
mgnatmake test_mod_64.adb
mgnatmake test_multidimensional_arrays.adb
mgnatmake test_numeric_exception.adb
mgnatmake test_pkg.adb
mgnatmake test_proc.adb
mgnatmake test_procedure_access.adb
mgnatmake test_record_array.adb
mgnatmake test_record_layout.adb
mgnatmake test_return_convert.adb
mgnatmake test_rounding.adb
mgnatmake test_scalar_rename.adb
mgnatmake test_seq_file.adb
mgnatmake test_slice_assign.adb
mgnatmake test_tag_attribute.adb
mgnatmake test_tag_record.adb
mgnatmake test_task.adb
mgnatmake test_task_.adb
mgnatmake test_task_string.adb
mgnatmake test_task_termination.adb
mgnatmake test_unchecked_conv.adb
mgnatmake test_valuetype.adb
mgnatmake test_valuetype_array.adb
mgnatmake test_wide.adb

@echo -------------------- TESTING -------------------- pause

peverify array_range.exe
peverify bug20030120a.exe
peverify bug20030120b.exe
peverify bug20030121a.exe
peverify bug20050830.exe
peverify echo_args.exe
peverify float_test.exe
peverify fred.exe
peverify hello.exe
pause
peverify hello_ada.exe
peverify hello_file.exe
peverify seq_io.exe
peverify test_array_bounds.exe
peverify test_assembly.exe
peverify test_assign.exe
peverify test_assign2.exe
peverify test_atc.exe
peverify test_attributes.exe
peverify test_bool_addrof.exe
pause
peverify test_byte_array.exe
peverify test_calendar.exe
peverify test_case.exe
peverify test_case2.exe
peverify test_case3.exe
peverify testcase2.exe
peverify testcase3.exe
peverify test_composite.exe
peverify test_controlled.exe
peverify test_device_error.exe
peverify test_direct_io.exe
peverify test_enum_attrib.exe
pause
peverify test_enum_get.exe
peverify test_environment.exe
peverify test_eof.exe
peverify test_exception.exe
peverify test_exports_main.exe
peverify test_file.exe
peverify test_file2.exe
peverify test_finalize.exe
peverify test_gen.exe
peverify test_generic_enum_main.exe
pause
peverify test_handling.exe
peverify test_interface.exe
peverify test_long_float.exe
peverify test_loop.exe
peverify test_lower.exe
peverify test_main.exe
peverify test_mod_64.exe
peverify test_multidimensional_arrays.exe
peverify test_numeric_exception.exe
peverify test_proc.exe
pause
peverify test_procedure_access.exe
peverify test_record_array.exe
peverify test_rounding.exe
peverify test_seq_file.exe
peverify test_slice_assign.exe
peverify test_tag_attribute.exe
peverify test_task.exe
peverify test_task_string.exe
peverify test_task_termination.exe
peverify test_unchecked_conv.exe
peverify test_valuetype.exe
pause
peverify test_valuetype_array.exe
peverify test_wide.exe
