-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.Collections.ICollection;
package MSSyst.ComponentModel.Design.Serialization.IDesignerSerializationService is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function Deserialize(
      This : access Typ;
      serializationData : access MSSyst.Object.Typ'Class) return access MSSyst.Collections.ICollection.Typ'Class is abstract;
   function Serialize(
      This : access Typ;
      objects : access MSSyst.Collections.ICollection.Typ'Class) return access MSSyst.Object.Typ'Class is abstract;
private
   pragma Import(MSIL,Deserialize,"Deserialize");
   pragma Import(MSIL,Serialize,"Serialize");
end MSSyst.ComponentModel.Design.Serialization.IDesignerSerializationService;
pragma Import(MSIL,MSSyst.ComponentModel.Design.Serialization.IDesignerSerializationService,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System]System.ComponentModel.Design.Serialization.IDesignerSerializationService");
