-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.ComponentModel.ITypeDescriptorContext;
limited with MSSyst.Drawing.Graphics;
limited with MSSyst.Drawing.Rectangle;
with MSSyst.EventArgs;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Drawing.Design.PaintValueEventArgs is
   type Typ is new MSSyst.EventArgs.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_PaintValueEventArgs(
      This : Ref := null;
      context : access MSSyst.ComponentModel.ITypeDescriptorContext.Typ'Class;
      value : access MSSyst.Object.Typ'Class;
      graphics : access MSSyst.Drawing.Graphics.Typ'Class;
      bounds : MSSyst.Drawing.Rectangle.Valuetype) return Ref;
   function get_Bounds(
      This : access Typ) return MSSyst.Drawing.Rectangle.Valuetype;
   function get_Context(
      This : access Typ) return access MSSyst.ComponentModel.ITypeDescriptorContext.Typ'Class;
   function get_Graphics(
      This : access Typ) return access MSSyst.Drawing.Graphics.Typ'Class;
   function get_Value(
      This : access Typ) return access MSSyst.Object.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_PaintValueEventArgs);
   pragma Import(MSIL,get_Bounds,"get_Bounds");
   pragma Import(MSIL,get_Context,"get_Context");
   pragma Import(MSIL,get_Graphics,"get_Graphics");
   pragma Import(MSIL,get_Value,"get_Value");
end MSSyst.Drawing.Design.PaintValueEventArgs;
pragma Import(MSIL,MSSyst.Drawing.Design.PaintValueEventArgs,
   ".ver 2:0:0:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[System.Drawing]System.Drawing.Design.PaintValueEventArgs");
