-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.ComponentModel.Component;
with MSSyst.ComponentModel.IComponent;
limited with MSSyst.ComponentModel.IContainer;
limited with MSSyst.ComponentModel.ISite;
limited with MSSyst.Drawing.Printing.PrintDocument;
limited with MSSyst.Drawing.Printing.PrinterSettings;
limited with MSSyst.EventHandler;
with MSSyst.IDisposable;
with MSSyst.MarshalByRefObject;
limited with MSSyst.Runtime.Remoting.ObjRef;
limited with MSSyst.String;
limited with MSSyst.Type_k;
with MSSyst.Windows.Forms.CommonDialog;
limited with MSSyst.Windows.Forms.DialogResult;
limited with MSSyst.Windows.Forms.IWin32Window;
package MSSyst.Windows.Forms.PrintDialog is
   type Typ is new MSSyst.Windows.Forms.CommonDialog.Typ
         and MSSyst.ComponentModel.IComponent.Typ
         and MSSyst.IDisposable.Typ
   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_PrintDialog(
      This : Ref := null) return Ref;
   function get_AllowCurrentPage(
      This : access Typ) return Standard.Boolean;
   function get_AllowPrintToFile(
      This : access Typ) return Standard.Boolean;
   function get_AllowSelection(
      This : access Typ) return Standard.Boolean;
   function get_AllowSomePages(
      This : access Typ) return Standard.Boolean;
   function get_Document(
      This : access Typ) return access MSSyst.Drawing.Printing.PrintDocument.Typ'Class;
   function get_PrinterSettings(
      This : access Typ) return access MSSyst.Drawing.Printing.PrinterSettings.Typ'Class;
   function get_PrintToFile(
      This : access Typ) return Standard.Boolean;
   function get_ShowHelp(
      This : access Typ) return Standard.Boolean;
   function get_ShowNetwork(
      This : access Typ) return Standard.Boolean;
   function get_UseEXDialog(
      This : access Typ) return Standard.Boolean;
   procedure Reset(
      This : access Typ);
   procedure set_AllowCurrentPage(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_AllowPrintToFile(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_AllowSelection(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_AllowSomePages(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_Document(
      This : access Typ;
      value : access MSSyst.Drawing.Printing.PrintDocument.Typ'Class);
   procedure set_PrinterSettings(
      This : access Typ;
      value : access MSSyst.Drawing.Printing.PrinterSettings.Typ'Class);
   procedure set_PrintToFile(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_ShowHelp(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_ShowNetwork(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_UseEXDialog(
      This : access Typ;
      value : Standard.Boolean);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_PrintDialog);
   pragma Import(MSIL,get_AllowCurrentPage,"get_AllowCurrentPage");
   pragma Import(MSIL,get_AllowPrintToFile,"get_AllowPrintToFile");
   pragma Import(MSIL,get_AllowSelection,"get_AllowSelection");
   pragma Import(MSIL,get_AllowSomePages,"get_AllowSomePages");
   pragma Import(MSIL,get_Document,"get_Document");
   pragma Import(MSIL,get_PrinterSettings,"get_PrinterSettings");
   pragma Import(MSIL,get_PrintToFile,"get_PrintToFile");
   pragma Import(MSIL,get_ShowHelp,"get_ShowHelp");
   pragma Import(MSIL,get_ShowNetwork,"get_ShowNetwork");
   pragma Import(MSIL,get_UseEXDialog,"get_UseEXDialog");
   pragma Import(MSIL,Reset,"Reset");
   pragma Import(MSIL,set_AllowCurrentPage,"set_AllowCurrentPage");
   pragma Import(MSIL,set_AllowPrintToFile,"set_AllowPrintToFile");
   pragma Import(MSIL,set_AllowSelection,"set_AllowSelection");
   pragma Import(MSIL,set_AllowSomePages,"set_AllowSomePages");
   pragma Import(MSIL,set_Document,"set_Document");
   pragma Import(MSIL,set_PrinterSettings,"set_PrinterSettings");
   pragma Import(MSIL,set_PrintToFile,"set_PrintToFile");
   pragma Import(MSIL,set_ShowHelp,"set_ShowHelp");
   pragma Import(MSIL,set_ShowNetwork,"set_ShowNetwork");
   pragma Import(MSIL,set_UseEXDialog,"set_UseEXDialog");
end MSSyst.Windows.Forms.PrintDialog;
pragma Import(MSIL,MSSyst.Windows.Forms.PrintDialog,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.PrintDialog");
