-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Attribute;
with MSSyst.Runtime.InteropServices.uAttribute;
limited with MSSyst.Security.IPermission;
with MSSyst.Security.Permissions.CodeAccessSecurityAttribute;
limited with MSSyst.Security.Permissions.SecurityAction;
with MSSyst.Security.Permissions.SecurityAttribute;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Security.Permissions.PublisherIdentityPermissionAttribute is
   type Typ is new MSSyst.Security.Permissions.CodeAccessSecurityAttribute.Typ
         and MSSyst.Runtime.InteropServices.uAttribute.Typ
   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_PublisherIdentityPermissionAttribute(
      This : Ref := null;
      action : MSSyst.Security.Permissions.SecurityAction.Valuetype) return Ref;
   function CreatePermission(
      This : access Typ) return access MSSyst.Security.IPermission.Typ'Class;
   function get_CertFile(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function get_SignedFile(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function get_X509Certificate(
      This : access Typ) return access MSSyst.String.Typ'Class;
   procedure set_CertFile(
      This : access Typ;
      value : access MSSyst.String.Typ'Class);
   procedure set_SignedFile(
      This : access Typ;
      value : access MSSyst.String.Typ'Class);
   procedure set_X509Certificate(
      This : access Typ;
      value : access MSSyst.String.Typ'Class);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_PublisherIdentityPermissionAttribute);
   pragma Import(MSIL,CreatePermission,"CreatePermission");
   pragma Import(MSIL,get_CertFile,"get_CertFile");
   pragma Import(MSIL,get_SignedFile,"get_SignedFile");
   pragma Import(MSIL,get_X509Certificate,"get_X509Certificate");
   pragma Import(MSIL,set_CertFile,"set_CertFile");
   pragma Import(MSIL,set_SignedFile,"set_SignedFile");
   pragma Import(MSIL,set_X509Certificate,"set_X509Certificate");
end MSSyst.Security.Permissions.PublisherIdentityPermissionAttribute;
pragma Import(MSIL,MSSyst.Security.Permissions.PublisherIdentityPermissionAttribute,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Security.Permissions.PublisherIdentityPermissionAttribute");
