-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.IFormatProvider;
limited with MSSyst.String;
limited with MSSyst.TypeCode;
limited with MSSyst.Type_k;
package MSSyst.Runtime.InteropServices.ComTypes.TYPEFLAGS is
   type ValueType is (
      TYPEFLAG_FAPPOBJECT,
      TYPEFLAG_FCANCREATE,
      TYPEFLAG_FLICENSED,
      TYPEFLAG_FPREDECLID,
      TYPEFLAG_FHIDDEN,
      TYPEFLAG_FCONTROL,
      TYPEFLAG_FDUAL,
      TYPEFLAG_FNONEXTENSIBLE,
      TYPEFLAG_FOLEAUTOMATION,
      TYPEFLAG_FRESTRICTED,
      TYPEFLAG_FAGGREGATABLE,
      TYPEFLAG_FREPLACEABLE,
      TYPEFLAG_FDISPATCHABLE,
      TYPEFLAG_FREVERSEBIND,
      TYPEFLAG_FPROXY);
   pragma Convention (MSIL, ValueType);
   for ValueType use (
      TYPEFLAG_FAPPOBJECT =>  0,
      TYPEFLAG_FCANCREATE =>  131074,
      TYPEFLAG_FLICENSED =>  262148,
      TYPEFLAG_FPREDECLID =>  524296,
      TYPEFLAG_FHIDDEN =>  1048592,
      TYPEFLAG_FCONTROL =>  2097184,
      TYPEFLAG_FDUAL =>  4194368,
      TYPEFLAG_FNONEXTENSIBLE =>  8388736,
      TYPEFLAG_FOLEAUTOMATION =>  16777472,
      TYPEFLAG_FRESTRICTED =>  33554944,
      TYPEFLAG_FAGGREGATABLE =>  67109888,
      TYPEFLAG_FREPLACEABLE =>  134219776,
      TYPEFLAG_FDISPATCHABLE =>  268439552,
      TYPEFLAG_FREVERSEBIND =>  536879104,
      TYPEFLAG_FPROXY =>  1073758208);
   type ValueType_Arr is array (Natural range <>) of ValueType; -- start at 0
   type ValueType_Array is access all ValueType_Arr;
   type ValueType_addrof is access all ValueType;
   type ValueType_array_addrof is access all ValueType_Array;
   function "+" (L,R : Valuetype) return Valuetype;
   pragma Import (MSIL, "+", "+");
   function CompareTo(
      This : Valuetype;
      target : access MSSyst.Object.Typ'Class) return Integer;
   function Equals(
      This : Valuetype;
      obj : access MSSyst.Object.Typ'Class) return Standard.Boolean;
   function GetHashCode(
      This : Valuetype) return Integer;
   function GetType(
      This : Valuetype) return access MSSyst.Type_k.Typ'Class;
   function GetTypeCode(
      This : Valuetype) return MSSyst.TypeCode.Valuetype;
   function ToString(
      This : Valuetype;
      provider : access MSSyst.IFormatProvider.Typ'Class) return access MSSyst.String.Typ'Class;
   function ToString(
      This : Valuetype) return access MSSyst.String.Typ'Class;
   function ToString(
      This : Valuetype;
      format : access MSSyst.String.Typ'Class;
      provider : access MSSyst.IFormatProvider.Typ'Class) return access MSSyst.String.Typ'Class;
   function ToString(
      This : Valuetype;
      format : access MSSyst.String.Typ'Class) return access MSSyst.String.Typ'Class;
private
   pragma Import(MSIL,CompareTo,"CompareTo");
   pragma Import(MSIL,Equals,"Equals");
   pragma Import(MSIL,GetHashCode,"GetHashCode");
   pragma Import(MSIL,GetType,"GetType");
   pragma Import(MSIL,GetTypeCode,"GetTypeCode");
   pragma Import(MSIL,ToString,"ToString");
end MSSyst.Runtime.InteropServices.ComTypes.TYPEFLAGS;
pragma Import(MSIL,MSSyst.Runtime.InteropServices.ComTypes.TYPEFLAGS,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Runtime.InteropServices.ComTypes.TYPEFLAGS");
