-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.ComponentModel.IComponent;
limited with MSSyst.ComponentModel.IContainer;
limited with MSSyst.ComponentModel.ISite;
limited with MSSyst.EventHandler;
with MSSyst.IDisposable;
with MSSyst.IServiceProvider;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.ComponentModel.MarshalByValueComponent is
   type Typ is new MSSyst.Object.Typ
         and MSSyst.ComponentModel.IComponent.Typ
         and MSSyst.IDisposable.Typ
         and MSSyst.IServiceProvider.Typ
   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_MarshalByValueComponent(
      This : Ref := null) return Ref;
   procedure add_Disposed(
      This : access Typ;
      value : access MSSyst.EventHandler.Typ'Class);
   procedure Dispose(
      This : access Typ);
   function get_Container(
      This : access Typ) return access MSSyst.ComponentModel.IContainer.Typ'Class;
   function get_DesignMode(
      This : access Typ) return Standard.Boolean;
   function get_Site(
      This : access Typ) return access MSSyst.ComponentModel.ISite.Typ'Class;
   function GetService(
      This : access Typ;
      service : access MSSyst.Type_k.Typ'Class) return access MSSyst.Object.Typ'Class;
   procedure remove_Disposed(
      This : access Typ;
      value : access MSSyst.EventHandler.Typ'Class);
   procedure set_Site(
      This : access Typ;
      value : access MSSyst.ComponentModel.ISite.Typ'Class);
   function ToString(
      This : access Typ) return access MSSyst.String.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_MarshalByValueComponent);
   pragma Import(MSIL,add_Disposed,"add_Disposed");
   pragma Import(MSIL,Dispose,"Dispose");
   pragma Import(MSIL,get_Container,"get_Container");
   pragma Import(MSIL,get_DesignMode,"get_DesignMode");
   pragma Import(MSIL,get_Site,"get_Site");
   pragma Import(MSIL,GetService,"GetService");
   pragma Import(MSIL,remove_Disposed,"remove_Disposed");
   pragma Import(MSIL,set_Site,"set_Site");
   pragma Import(MSIL,ToString,"ToString");
end MSSyst.ComponentModel.MarshalByValueComponent;
pragma Import(MSIL,MSSyst.ComponentModel.MarshalByValueComponent,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System]System.ComponentModel.MarshalByValueComponent");
