-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.MarshalByRefObject;
limited with MSSyst.Reflection.AssemblyName;
limited with MSSyst.Runtime.Remoting.ObjRef;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Reflection.AssemblyNameProxy is
   type Typ is new MSSyst.MarshalByRefObject.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_AssemblyNameProxy(
      This : Ref := null) return Ref;
   function GetAssemblyName(
      This : access Typ;
      assemblyFile : access MSSyst.String.Typ'Class) return access MSSyst.Reflection.AssemblyName.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_AssemblyNameProxy);
   pragma Import(MSIL,GetAssemblyName,"GetAssemblyName");
end MSSyst.Reflection.AssemblyNameProxy;
pragma Import(MSIL,MSSyst.Reflection.AssemblyNameProxy,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Reflection.AssemblyNameProxy");
