-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
package MSSyst.Runtime.Remoting.Channels.ISecurableChannel is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function get_IsSecured(
      This : access Typ) return Standard.Boolean is abstract;
   procedure set_IsSecured(
      This : access Typ;
      value : Standard.Boolean) is abstract;
private
   pragma Import(MSIL,get_IsSecured,"get_IsSecured");
   pragma Import(MSIL,set_IsSecured,"set_IsSecured");
end MSSyst.Runtime.Remoting.Channels.ISecurableChannel;
pragma Import(MSIL,MSSyst.Runtime.Remoting.Channels.ISecurableChannel,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Runtime.Remoting.Channels.ISecurableChannel");
