-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.ComponentModel.IComponent;
limited with MSSyst.ComponentModel.ISite;
limited with MSSyst.EventHandler;
with MSSyst.ICloneable;
with MSSyst.IDisposable;
limited with MSSyst.String;
limited with MSSyst.Type_k;
limited with MSSyst.Windows.Forms.ContextMenuStrip;
limited with MSSyst.Windows.Forms.DataGridViewAutoSizeColumnMode;
with MSSyst.Windows.Forms.DataGridViewBand;
limited with MSSyst.Windows.Forms.DataGridViewCellStyle;
limited with MSSyst.Windows.Forms.DataGridViewCell;
with MSSyst.Windows.Forms.DataGridViewColumn;
limited with MSSyst.Windows.Forms.DataGridViewColumnHeaderCell;
limited with MSSyst.Windows.Forms.DataGridViewColumnSortMode;
limited with MSSyst.Windows.Forms.DataGridViewComboBoxCell.ObjectCollection;
limited with MSSyst.Windows.Forms.DataGridViewComboBoxDisplayStyle;
with MSSyst.Windows.Forms.DataGridViewElement;
limited with MSSyst.Windows.Forms.DataGridViewElementStates;
limited with MSSyst.Windows.Forms.DataGridViewTriState;
limited with MSSyst.Windows.Forms.DataGridView;
limited with MSSyst.Windows.Forms.FlatStyle;
package MSSyst.Windows.Forms.DataGridViewComboBoxColumn is
   type Typ is new MSSyst.Windows.Forms.DataGridViewColumn.Typ
         and MSSyst.ICloneable.Typ
         and MSSyst.IDisposable.Typ
         and MSSyst.ComponentModel.IComponent.Typ
   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_DataGridViewComboBoxColumn(
      This : Ref := null) return Ref;
   function Clone(
      This : access Typ) return access MSSyst.Object.Typ'Class;
   function get_AutoComplete(
      This : access Typ) return Standard.Boolean;
   function get_CellTemplate(
      This : access Typ) return access MSSyst.Windows.Forms.DataGridViewCell.Typ'Class;
   function get_DataSource(
      This : access Typ) return access MSSyst.Object.Typ'Class;
   function get_DisplayMember(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function get_DisplayStyle(
      This : access Typ) return MSSyst.Windows.Forms.DataGridViewComboBoxDisplayStyle.Valuetype;
   function get_DisplayStyleForCurrentCellOnly(
      This : access Typ) return Standard.Boolean;
   function get_DropDownWidth(
      This : access Typ) return Integer;
   function get_FlatStyle(
      This : access Typ) return MSSyst.Windows.Forms.FlatStyle.Valuetype;
   function get_Items(
      This : access Typ) return access MSSyst.Windows.Forms.DataGridViewComboBoxCell.ObjectCollection.Typ'Class;
   function get_MaxDropDownItems(
      This : access Typ) return Integer;
   function get_Sorted(
      This : access Typ) return Standard.Boolean;
   function get_ValueMember(
      This : access Typ) return access MSSyst.String.Typ'Class;
   procedure set_AutoComplete(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_CellTemplate(
      This : access Typ;
      value : access MSSyst.Windows.Forms.DataGridViewCell.Typ'Class);
   procedure set_DataSource(
      This : access Typ;
      value : access MSSyst.Object.Typ'Class);
   procedure set_DisplayMember(
      This : access Typ;
      value : access MSSyst.String.Typ'Class);
   procedure set_DisplayStyle(
      This : access Typ;
      value : MSSyst.Windows.Forms.DataGridViewComboBoxDisplayStyle.Valuetype);
   procedure set_DisplayStyleForCurrentCellOnly(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_DropDownWidth(
      This : access Typ;
      value : Integer);
   procedure set_FlatStyle(
      This : access Typ;
      value : MSSyst.Windows.Forms.FlatStyle.Valuetype);
   procedure set_MaxDropDownItems(
      This : access Typ;
      value : Integer);
   procedure set_Sorted(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_ValueMember(
      This : access Typ;
      value : access MSSyst.String.Typ'Class);
   function ToString(
      This : access Typ) return access MSSyst.String.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_DataGridViewComboBoxColumn);
   pragma Import(MSIL,Clone,"Clone");
   pragma Import(MSIL,get_AutoComplete,"get_AutoComplete");
   pragma Import(MSIL,get_CellTemplate,"get_CellTemplate");
   pragma Import(MSIL,get_DataSource,"get_DataSource");
   pragma Import(MSIL,get_DisplayMember,"get_DisplayMember");
   pragma Import(MSIL,get_DisplayStyle,"get_DisplayStyle");
   pragma Import(MSIL,get_DisplayStyleForCurrentCellOnly,"get_DisplayStyleForCurrentCellOnly");
   pragma Import(MSIL,get_DropDownWidth,"get_DropDownWidth");
   pragma Import(MSIL,get_FlatStyle,"get_FlatStyle");
   pragma Import(MSIL,get_Items,"get_Items");
   pragma Import(MSIL,get_MaxDropDownItems,"get_MaxDropDownItems");
   pragma Import(MSIL,get_Sorted,"get_Sorted");
   pragma Import(MSIL,get_ValueMember,"get_ValueMember");
   pragma Import(MSIL,set_AutoComplete,"set_AutoComplete");
   pragma Import(MSIL,set_CellTemplate,"set_CellTemplate");
   pragma Import(MSIL,set_DataSource,"set_DataSource");
   pragma Import(MSIL,set_DisplayMember,"set_DisplayMember");
   pragma Import(MSIL,set_DisplayStyle,"set_DisplayStyle");
   pragma Import(MSIL,set_DisplayStyleForCurrentCellOnly,"set_DisplayStyleForCurrentCellOnly");
   pragma Import(MSIL,set_DropDownWidth,"set_DropDownWidth");
   pragma Import(MSIL,set_FlatStyle,"set_FlatStyle");
   pragma Import(MSIL,set_MaxDropDownItems,"set_MaxDropDownItems");
   pragma Import(MSIL,set_Sorted,"set_Sorted");
   pragma Import(MSIL,set_ValueMember,"set_ValueMember");
   pragma Import(MSIL,ToString,"ToString");
end MSSyst.Windows.Forms.DataGridViewComboBoxColumn;
pragma Import(MSIL,MSSyst.Windows.Forms.DataGridViewComboBoxColumn,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.DataGridViewComboBoxColumn");
