-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.Drawing.Size;
limited with MSSyst.String;
limited with MSSyst.Type_k;
with MSSyst.ValueType;
package MSSyst.Windows.Forms.Padding is
   type ValueType is new MSSyst.ValueType.Typ with null record;
   type ValueType_Arr is array (Natural range <>) of ValueType; -- start at 0
   type ValueType_Array is access all ValueType_Arr;
   type ValueType_addrof is access all ValueType;
   type ValueType_array_addrof is access all ValueType_Array;
   function new_Padding(
      all_k : Integer) return Valuetype;
   function new_Padding(
      left : Integer;
      top : Integer;
      right : Integer;
      bottom : Integer) return Valuetype;
   function Add(
      p1 : MSSyst.Windows.Forms.Padding.Valuetype;
      p2 : MSSyst.Windows.Forms.Padding.Valuetype) return MSSyst.Windows.Forms.Padding.Valuetype;
   function Equals(
      This : Valuetype;
      other : access MSSyst.Object.Typ'Class) return Standard.Boolean;
   function get_All(
      This : Valuetype) return Integer;
   function get_Bottom(
      This : Valuetype) return Integer;
   function get_Horizontal(
      This : Valuetype) return Integer;
   function get_Left(
      This : Valuetype) return Integer;
   function get_Right(
      This : Valuetype) return Integer;
   function get_Size(
      This : Valuetype) return MSSyst.Drawing.Size.Valuetype;
   function get_Top(
      This : Valuetype) return Integer;
   function get_Vertical(
      This : Valuetype) return Integer;
   function GetHashCode(
      This : Valuetype) return Integer;
   function op_Addition(
      p1 : MSSyst.Windows.Forms.Padding.Valuetype;
      p2 : MSSyst.Windows.Forms.Padding.Valuetype) return MSSyst.Windows.Forms.Padding.Valuetype;
   function op_Equality(
      p1 : MSSyst.Windows.Forms.Padding.Valuetype;
      p2 : MSSyst.Windows.Forms.Padding.Valuetype) return Standard.Boolean;
   function op_Inequality(
      p1 : MSSyst.Windows.Forms.Padding.Valuetype;
      p2 : MSSyst.Windows.Forms.Padding.Valuetype) return Standard.Boolean;
   function op_Subtraction(
      p1 : MSSyst.Windows.Forms.Padding.Valuetype;
      p2 : MSSyst.Windows.Forms.Padding.Valuetype) return MSSyst.Windows.Forms.Padding.Valuetype;
   procedure set_All(
      This : Valuetype;
      value : Integer);
   procedure set_Bottom(
      This : Valuetype;
      value : Integer);
   procedure set_Left(
      This : Valuetype;
      value : Integer);
   procedure set_Right(
      This : Valuetype;
      value : Integer);
   procedure set_Top(
      This : Valuetype;
      value : Integer);
   function Subtract(
      p1 : MSSyst.Windows.Forms.Padding.Valuetype;
      p2 : MSSyst.Windows.Forms.Padding.Valuetype) return MSSyst.Windows.Forms.Padding.Valuetype;
   function ToString(
      This : Valuetype) return access MSSyst.String.Typ'Class;
private
   pragma MSIL_Constructor(new_Padding);
   pragma Import(MSIL,Add,"Add");
   pragma Import(MSIL,Equals,"Equals");
   pragma Import(MSIL,get_All,"get_All");
   pragma Import(MSIL,get_Bottom,"get_Bottom");
   pragma Import(MSIL,get_Horizontal,"get_Horizontal");
   pragma Import(MSIL,get_Left,"get_Left");
   pragma Import(MSIL,get_Right,"get_Right");
   pragma Import(MSIL,get_Size,"get_Size");
   pragma Import(MSIL,get_Top,"get_Top");
   pragma Import(MSIL,get_Vertical,"get_Vertical");
   pragma Import(MSIL,GetHashCode,"GetHashCode");
   pragma Import(MSIL,op_Addition,"op_Addition");
   pragma Import(MSIL,op_Equality,"op_Equality");
   pragma Import(MSIL,op_Inequality,"op_Inequality");
   pragma Import(MSIL,op_Subtraction,"op_Subtraction");
   pragma Import(MSIL,set_All,"set_All");
   pragma Import(MSIL,set_Bottom,"set_Bottom");
   pragma Import(MSIL,set_Left,"set_Left");
   pragma Import(MSIL,set_Right,"set_Right");
   pragma Import(MSIL,set_Top,"set_Top");
   pragma Import(MSIL,Subtract,"Subtract");
   pragma Import(MSIL,ToString,"ToString");
end MSSyst.Windows.Forms.Padding;
pragma Import(MSIL,MSSyst.Windows.Forms.Padding,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.Padding");
