-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.IO.DirectoryInfo;
limited with MSSyst.IO.DriveType;
with MSSyst.Runtime.Serialization.ISerializable;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.IO.DriveInfo is
   type Typ is new MSSyst.Object.Typ
         and MSSyst.Runtime.Serialization.ISerializable.Typ
   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_DriveInfo(
      This : Ref := null;
      driveName : access MSSyst.String.Typ'Class) return Ref;
   function get_AvailableFreeSpace(
      This : access Typ) return Long_Long_Integer;
   function get_DriveFormat(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function get_DriveType(
      This : access Typ) return MSSyst.IO.DriveType.Valuetype;
   function get_IsReady(
      This : access Typ) return Standard.Boolean;
   function get_Name(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function get_RootDirectory(
      This : access Typ) return access MSSyst.IO.DirectoryInfo.Typ'Class;
   function get_TotalFreeSpace(
      This : access Typ) return Long_Long_Integer;
   function get_TotalSize(
      This : access Typ) return Long_Long_Integer;
   function get_VolumeLabel(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function GetDrives return access MSSyst.IO.DriveInfo.Ref_arr;
   procedure set_VolumeLabel(
      This : access Typ;
      value : access MSSyst.String.Typ'Class);
   function ToString(
      This : access Typ) return access MSSyst.String.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_DriveInfo);
   pragma Import(MSIL,get_AvailableFreeSpace,"get_AvailableFreeSpace");
   pragma Import(MSIL,get_DriveFormat,"get_DriveFormat");
   pragma Import(MSIL,get_DriveType,"get_DriveType");
   pragma Import(MSIL,get_IsReady,"get_IsReady");
   pragma Import(MSIL,get_Name,"get_Name");
   pragma Import(MSIL,get_RootDirectory,"get_RootDirectory");
   pragma Import(MSIL,get_TotalFreeSpace,"get_TotalFreeSpace");
   pragma Import(MSIL,get_TotalSize,"get_TotalSize");
   pragma Import(MSIL,get_VolumeLabel,"get_VolumeLabel");
   pragma Import(MSIL,GetDrives,"GetDrives");
   pragma Import(MSIL,set_VolumeLabel,"set_VolumeLabel");
   pragma Import(MSIL,ToString,"ToString");
end MSSyst.IO.DriveInfo;
pragma Import(MSIL,MSSyst.IO.DriveInfo,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.IO.DriveInfo");
