-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.Collections.IDictionary;
limited with MSSyst.ComponentModel.Design.CommandID;
with MSSyst.ComponentModel.Design.MenuCommand;
limited with MSSyst.EventHandler;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.ComponentModel.Design.DesignerVerb is
   type Typ is new MSSyst.ComponentModel.Design.MenuCommand.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_DesignerVerb(
      This : Ref := null;
      text : access MSSyst.String.Typ'Class;
      handler : access MSSyst.EventHandler.Typ'Class) return Ref;
   function new_DesignerVerb(
      This : Ref := null;
      text : access MSSyst.String.Typ'Class;
      handler : access MSSyst.EventHandler.Typ'Class;
      startCommandID : access MSSyst.ComponentModel.Design.CommandID.Typ'Class) return Ref;
   function get_Description(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function get_Text(
      This : access Typ) return access MSSyst.String.Typ'Class;
   procedure set_Description(
      This : access Typ;
      value : access MSSyst.String.Typ'Class);
   function ToString(
      This : access Typ) return access MSSyst.String.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_DesignerVerb);
   pragma Import(MSIL,get_Description,"get_Description");
   pragma Import(MSIL,get_Text,"get_Text");
   pragma Import(MSIL,set_Description,"set_Description");
   pragma Import(MSIL,ToString,"ToString");
end MSSyst.ComponentModel.Design.DesignerVerb;
pragma Import(MSIL,MSSyst.ComponentModel.Design.DesignerVerb,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System]System.ComponentModel.Design.DesignerVerb");
