-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
package MSSyst.Runtime.InteropServices.ICustomMarshaler is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure CleanUpManagedData(
      This : access Typ;
      ManagedObj : access MSSyst.Object.Typ'Class) is abstract;
   procedure CleanUpNativeData(
      This : access Typ;
      pNativeData : MSIL_Types.native_int) is abstract;
   function GetNativeDataSize(
      This : access Typ) return Integer is abstract;
   function MarshalManagedToNative(
      This : access Typ;
      ManagedObj : access MSSyst.Object.Typ'Class) return MSIL_Types.native_int is abstract;
   function MarshalNativeToManaged(
      This : access Typ;
      pNativeData : MSIL_Types.native_int) return access MSSyst.Object.Typ'Class is abstract;
private
   pragma Import(MSIL,CleanUpManagedData,"CleanUpManagedData");
   pragma Import(MSIL,CleanUpNativeData,"CleanUpNativeData");
   pragma Import(MSIL,GetNativeDataSize,"GetNativeDataSize");
   pragma Import(MSIL,MarshalManagedToNative,"MarshalManagedToNative");
   pragma Import(MSIL,MarshalNativeToManaged,"MarshalNativeToManaged");
end MSSyst.Runtime.InteropServices.ICustomMarshaler;
pragma Import(MSIL,MSSyst.Runtime.InteropServices.ICustomMarshaler,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Runtime.InteropServices.ICustomMarshaler");
