-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Collections.ICollection;
with MSSyst.Collections.IEnumerable;
limited with MSSyst.Security.AccessControl.AceEnumerator;
limited with MSSyst.Security.AccessControl.GenericAce;
with MSSyst.Security.AccessControl.GenericAcl;
limited with MSSyst.Security.Principal.SecurityIdentifier;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Security.AccessControl.CommonAcl is
   type Typ is abstract new MSSyst.Security.AccessControl.GenericAcl.Typ
         and MSSyst.Collections.ICollection.Typ
         and MSSyst.Collections.IEnumerable.Typ
   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function get_BinaryLength(
      This : access Typ) return Integer;
   function get_Count(
      This : access Typ) return Integer;
   function get_IsCanonical(
      This : access Typ) return Standard.Boolean;
   function get_IsContainer(
      This : access Typ) return Standard.Boolean;
   function get_IsDS(
      This : access Typ) return Standard.Boolean;
   function get_Item(
      This : access Typ;
      index : Integer) return access MSSyst.Security.AccessControl.GenericAce.Typ'Class;
   function get_Revision(
      This : access Typ) return MSIL_Types.unsigned_int8;
   procedure GetBinaryForm(
      This : access Typ;
      binaryForm : MSIL_Types.unsigned_int8_Arr;
      offset : Integer);
   procedure Purge(
      This : access Typ;
      sid : access MSSyst.Security.Principal.SecurityIdentifier.Typ'Class);
   procedure RemoveInheritedAces(
      This : access Typ);
   procedure set_Item(
      This : access Typ;
      index : Integer;
      value : access MSSyst.Security.AccessControl.GenericAce.Typ'Class);
private
   pragma Convention(MSIL,Typ);
   pragma Import(MSIL,get_BinaryLength,"get_BinaryLength");
   pragma Import(MSIL,get_Count,"get_Count");
   pragma Import(MSIL,get_IsCanonical,"get_IsCanonical");
   pragma Import(MSIL,get_IsContainer,"get_IsContainer");
   pragma Import(MSIL,get_IsDS,"get_IsDS");
   pragma Import(MSIL,get_Item,"get_Item");
   pragma Import(MSIL,get_Revision,"get_Revision");
   pragma Import(MSIL,GetBinaryForm,"GetBinaryForm");
   pragma Import(MSIL,Purge,"Purge");
   pragma Import(MSIL,RemoveInheritedAces,"RemoveInheritedAces");
   pragma Import(MSIL,set_Item,"set_Item");
end MSSyst.Security.AccessControl.CommonAcl;
pragma Import(MSIL,MSSyst.Security.AccessControl.CommonAcl,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Security.AccessControl.CommonAcl");
