-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.IDisposable;
limited with MSSyst.IO.Stream;
with MSSyst.Security.Cryptography.HMAC;
with MSSyst.Security.Cryptography.HashAlgorithm;
with MSSyst.Security.Cryptography.ICryptoTransform;
with MSSyst.Security.Cryptography.KeyedHashAlgorithm;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Security.Cryptography.HMACMD5 is
   type Typ is new MSSyst.Security.Cryptography.HMAC.Typ
         and MSSyst.Security.Cryptography.ICryptoTransform.Typ
         and MSSyst.IDisposable.Typ
   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_HMACMD5(
      This : Ref := null) return Ref;
   function new_HMACMD5(
      This : Ref := null;
      key : MSIL_Types.unsigned_int8_Arr) return Ref;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_HMACMD5);
end MSSyst.Security.Cryptography.HMACMD5;
pragma Import(MSIL,MSSyst.Security.Cryptography.HMACMD5,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Security.Cryptography.HMACMD5");
