-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.Net.IPEndPoint;
limited with MSSyst.Net.NetworkInformation.IPGlobalStatistics;
limited with MSSyst.Net.NetworkInformation.IcmpV4Statistics;
limited with MSSyst.Net.NetworkInformation.IcmpV6Statistics;
limited with MSSyst.Net.NetworkInformation.NetBiosNodeType;
limited with MSSyst.Net.NetworkInformation.TcpConnectionInformation;
limited with MSSyst.Net.NetworkInformation.TcpStatistics;
limited with MSSyst.Net.NetworkInformation.UdpStatistics;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Net.NetworkInformation.IPGlobalProperties is
   type Typ is abstract new MSSyst.Object.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function get_DhcpScopeName(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function get_DomainName(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function get_HostName(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function get_IsWinsProxy(
      This : access Typ) return Standard.Boolean;
   function get_NodeType(
      This : access Typ) return MSSyst.Net.NetworkInformation.NetBiosNodeType.Valuetype;
   function GetActiveTcpConnections(
      This : access Typ) return access MSSyst.Net.NetworkInformation.TcpConnectionInformation.Ref_arr;
   function GetActiveTcpListeners(
      This : access Typ) return access MSSyst.Net.IPEndPoint.Ref_arr;
   function GetActiveUdpListeners(
      This : access Typ) return access MSSyst.Net.IPEndPoint.Ref_arr;
   function GetIcmpV4Statistics(
      This : access Typ) return access MSSyst.Net.NetworkInformation.IcmpV4Statistics.Typ'Class;
   function GetIcmpV6Statistics(
      This : access Typ) return access MSSyst.Net.NetworkInformation.IcmpV6Statistics.Typ'Class;
   function GetIPGlobalProperties return access MSSyst.Net.NetworkInformation.IPGlobalProperties.Typ'Class;
   function GetIPv4GlobalStatistics(
      This : access Typ) return access MSSyst.Net.NetworkInformation.IPGlobalStatistics.Typ'Class;
   function GetIPv6GlobalStatistics(
      This : access Typ) return access MSSyst.Net.NetworkInformation.IPGlobalStatistics.Typ'Class;
   function GetTcpIPv4Statistics(
      This : access Typ) return access MSSyst.Net.NetworkInformation.TcpStatistics.Typ'Class;
   function GetTcpIPv6Statistics(
      This : access Typ) return access MSSyst.Net.NetworkInformation.TcpStatistics.Typ'Class;
   function GetUdpIPv4Statistics(
      This : access Typ) return access MSSyst.Net.NetworkInformation.UdpStatistics.Typ'Class;
   function GetUdpIPv6Statistics(
      This : access Typ) return access MSSyst.Net.NetworkInformation.UdpStatistics.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma Import(MSIL,get_DhcpScopeName,"get_DhcpScopeName");
   pragma Import(MSIL,get_DomainName,"get_DomainName");
   pragma Import(MSIL,get_HostName,"get_HostName");
   pragma Import(MSIL,get_IsWinsProxy,"get_IsWinsProxy");
   pragma Import(MSIL,get_NodeType,"get_NodeType");
   pragma Import(MSIL,GetActiveTcpConnections,"GetActiveTcpConnections");
   pragma Import(MSIL,GetActiveTcpListeners,"GetActiveTcpListeners");
   pragma Import(MSIL,GetActiveUdpListeners,"GetActiveUdpListeners");
   pragma Import(MSIL,GetIcmpV4Statistics,"GetIcmpV4Statistics");
   pragma Import(MSIL,GetIcmpV6Statistics,"GetIcmpV6Statistics");
   pragma Import(MSIL,GetIPGlobalProperties,"GetIPGlobalProperties");
   pragma Import(MSIL,GetIPv4GlobalStatistics,"GetIPv4GlobalStatistics");
   pragma Import(MSIL,GetIPv6GlobalStatistics,"GetIPv6GlobalStatistics");
   pragma Import(MSIL,GetTcpIPv4Statistics,"GetTcpIPv4Statistics");
   pragma Import(MSIL,GetTcpIPv6Statistics,"GetTcpIPv6Statistics");
   pragma Import(MSIL,GetUdpIPv4Statistics,"GetUdpIPv4Statistics");
   pragma Import(MSIL,GetUdpIPv6Statistics,"GetUdpIPv6Statistics");
end MSSyst.Net.NetworkInformation.IPGlobalProperties;
pragma Import(MSIL,MSSyst.Net.NetworkInformation.IPGlobalProperties,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System]System.Net.NetworkInformation.IPGlobalProperties");
