-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.IDisposable;
package MSSyst.Security.Cryptography.ICryptoTransform is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function get_CanReuseTransform(
      This : access Typ) return Standard.Boolean is abstract;
   function get_CanTransformMultipleBlocks(
      This : access Typ) return Standard.Boolean is abstract;
   function get_InputBlockSize(
      This : access Typ) return Integer is abstract;
   function get_OutputBlockSize(
      This : access Typ) return Integer is abstract;
   function TransformBlock(
      This : access Typ;
      inputBuffer : MSIL_Types.unsigned_int8_Arr;
      inputOffset : Integer;
      inputCount : Integer;
      outputBuffer : MSIL_Types.unsigned_int8_Arr;
      outputOffset : Integer) return Integer is abstract;
   function TransformFinalBlock(
      This : access Typ;
      inputBuffer : MSIL_Types.unsigned_int8_Arr;
      inputOffset : Integer;
      inputCount : Integer) return MSIL_Types.unsigned_int8_Array is abstract;
private
   pragma Import(MSIL,get_CanReuseTransform,"get_CanReuseTransform");
   pragma Import(MSIL,get_CanTransformMultipleBlocks,"get_CanTransformMultipleBlocks");
   pragma Import(MSIL,get_InputBlockSize,"get_InputBlockSize");
   pragma Import(MSIL,get_OutputBlockSize,"get_OutputBlockSize");
   pragma Import(MSIL,TransformBlock,"TransformBlock");
   pragma Import(MSIL,TransformFinalBlock,"TransformFinalBlock");
end MSSyst.Security.Cryptography.ICryptoTransform;
pragma Import(MSIL,MSSyst.Security.Cryptography.ICryptoTransform,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Security.Cryptography.ICryptoTransform");
