-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Windows.Forms.UnsafeNativeMethods;
package MSSyst.Windows.Forms.UnsafeNativeMethods.IOleDropTarget is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function OleDragEnter(
      This : access Typ;
      pDataObj : access MSSyst.Object.Typ'Class;
      grfKeyState : Integer;
      pt : Long_Long_Integer;
      pdwEffect : MSIL_Types.Int32_addrof) return Integer is abstract;
   function OleDragLeave(
      This : access Typ) return Integer is abstract;
   function OleDragOver(
      This : access Typ;
      grfKeyState : Integer;
      pt : Long_Long_Integer;
      pdwEffect : MSIL_Types.Int32_addrof) return Integer is abstract;
   function OleDrop(
      This : access Typ;
      pDataObj : access MSSyst.Object.Typ'Class;
      grfKeyState : Integer;
      pt : Long_Long_Integer;
      pdwEffect : MSIL_Types.Int32_addrof) return Integer is abstract;
private
   pragma Import(MSIL,OleDragEnter,"OleDragEnter");
   pragma Import(MSIL,OleDragLeave,"OleDragLeave");
   pragma Import(MSIL,OleDragOver,"OleDragOver");
   pragma Import(MSIL,OleDrop,"OleDrop");
end MSSyst.Windows.Forms.UnsafeNativeMethods.IOleDropTarget;
pragma Import(MSIL,MSSyst.Windows.Forms.UnsafeNativeMethods.IOleDropTarget,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.UnsafeNativeMethods/IOleDropTarget");
