-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.ComponentModel.CancelEventArgs;
with MSSyst.EventArgs;
limited with MSSyst.Globalization.CultureInfo;
limited with MSSyst.String;
limited with MSSyst.Type_k;
limited with MSSyst.Windows.Forms.InputLanguage;
package MSSyst.Windows.Forms.InputLanguageChangingEventArgs is
   type Typ is new MSSyst.ComponentModel.CancelEventArgs.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_InputLanguageChangingEventArgs(
      This : Ref := null;
      culture : access MSSyst.Globalization.CultureInfo.Typ'Class;
      sysCharSet : Standard.Boolean) return Ref;
   function new_InputLanguageChangingEventArgs(
      This : Ref := null;
      inputLanguage : access MSSyst.Windows.Forms.InputLanguage.Typ'Class;
      sysCharSet : Standard.Boolean) return Ref;
   function get_Culture(
      This : access Typ) return access MSSyst.Globalization.CultureInfo.Typ'Class;
   function get_InputLanguage(
      This : access Typ) return access MSSyst.Windows.Forms.InputLanguage.Typ'Class;
   function get_SysCharSet(
      This : access Typ) return Standard.Boolean;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_InputLanguageChangingEventArgs);
   pragma Import(MSIL,get_Culture,"get_Culture");
   pragma Import(MSIL,get_InputLanguage,"get_InputLanguage");
   pragma Import(MSIL,get_SysCharSet,"get_SysCharSet");
end MSSyst.Windows.Forms.InputLanguageChangingEventArgs;
pragma Import(MSIL,MSSyst.Windows.Forms.InputLanguageChangingEventArgs,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.InputLanguageChangingEventArgs");
