-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.ComponentModel.Component;
with MSSyst.ComponentModel.IComponent;
limited with MSSyst.ComponentModel.IContainer;
limited with MSSyst.ComponentModel.ISite;
limited with MSSyst.EventHandler;
with MSSyst.IDisposable;
with MSSyst.MarshalByRefObject;
limited with MSSyst.Runtime.Remoting.ObjRef;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Windows.Forms.Timer is
   type Typ is new MSSyst.ComponentModel.Component.Typ
         and MSSyst.ComponentModel.IComponent.Typ
         and MSSyst.IDisposable.Typ
   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_Timer(
      This : Ref := null) return Ref;
   function new_Timer(
      This : Ref := null;
      container : access MSSyst.ComponentModel.IContainer.Typ'Class) return Ref;
   procedure add_Tick(
      This : access Typ;
      value : access MSSyst.EventHandler.Typ'Class);
   function get_Enabled(
      This : access Typ) return Standard.Boolean;
   function get_Interval(
      This : access Typ) return Integer;
   function get_Tag(
      This : access Typ) return access MSSyst.Object.Typ'Class;
   procedure remove_Tick(
      This : access Typ;
      value : access MSSyst.EventHandler.Typ'Class);
   procedure set_Enabled(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_Interval(
      This : access Typ;
      value : Integer);
   procedure set_Tag(
      This : access Typ;
      value : access MSSyst.Object.Typ'Class);
   procedure Start(
      This : access Typ);
   procedure Stop(
      This : access Typ);
   function ToString(
      This : access Typ) return access MSSyst.String.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_Timer);
   pragma Import(MSIL,add_Tick,"add_Tick");
   pragma Import(MSIL,get_Enabled,"get_Enabled");
   pragma Import(MSIL,get_Interval,"get_Interval");
   pragma Import(MSIL,get_Tag,"get_Tag");
   pragma Import(MSIL,remove_Tick,"remove_Tick");
   pragma Import(MSIL,set_Enabled,"set_Enabled");
   pragma Import(MSIL,set_Interval,"set_Interval");
   pragma Import(MSIL,set_Tag,"set_Tag");
   pragma Import(MSIL,Start,"Start");
   pragma Import(MSIL,Stop,"Stop");
   pragma Import(MSIL,ToString,"ToString");
end MSSyst.Windows.Forms.Timer;
pragma Import(MSIL,MSSyst.Windows.Forms.Timer,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.Timer");
