-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.Configuration.SettingsProperty;
limited with MSSyst.Configuration.SettingsProvider;
package MSSyst.Configuration.ISettingsProviderService is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function GetSettingsProvider(
      This : access Typ;
      property : access MSSyst.Configuration.SettingsProperty.Typ'Class) return access MSSyst.Configuration.SettingsProvider.Typ'Class is abstract;
private
   pragma Import(MSIL,GetSettingsProvider,"GetSettingsProvider");
end MSSyst.Configuration.ISettingsProviderService;
pragma Import(MSIL,MSSyst.Configuration.ISettingsProviderService,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System]System.Configuration.ISettingsProviderService");
