-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.ComponentModel.CancelEventArgs;
with MSSyst.EventArgs;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Windows.Forms.SplitterCancelEventArgs is
   type Typ is new MSSyst.ComponentModel.CancelEventArgs.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_SplitterCancelEventArgs(
      This : Ref := null;
      mouseCursorX : Integer;
      mouseCursorY : Integer;
      splitX : Integer;
      splitY : Integer) return Ref;
   function get_MouseCursorX(
      This : access Typ) return Integer;
   function get_MouseCursorY(
      This : access Typ) return Integer;
   function get_SplitX(
      This : access Typ) return Integer;
   function get_SplitY(
      This : access Typ) return Integer;
   procedure set_SplitX(
      This : access Typ;
      value : Integer);
   procedure set_SplitY(
      This : access Typ;
      value : Integer);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_SplitterCancelEventArgs);
   pragma Import(MSIL,get_MouseCursorX,"get_MouseCursorX");
   pragma Import(MSIL,get_MouseCursorY,"get_MouseCursorY");
   pragma Import(MSIL,get_SplitX,"get_SplitX");
   pragma Import(MSIL,get_SplitY,"get_SplitY");
   pragma Import(MSIL,set_SplitX,"set_SplitX");
   pragma Import(MSIL,set_SplitY,"set_SplitY");
end MSSyst.Windows.Forms.SplitterCancelEventArgs;
pragma Import(MSIL,MSSyst.Windows.Forms.SplitterCancelEventArgs,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.SplitterCancelEventArgs");
