-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Attribute;
with MSSyst.Runtime.InteropServices.uAttribute;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Runtime.Remoting.Metadata.SoapAttribute is
   type Typ is new MSSyst.Attribute.Typ
         and MSSyst.Runtime.InteropServices.uAttribute.Typ
   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_SoapAttribute(
      This : Ref := null) return Ref;
   function get_Embedded(
      This : access Typ) return Standard.Boolean;
   function get_UseAttribute(
      This : access Typ) return Standard.Boolean;
   function get_XmlNamespace(
      This : access Typ) return access MSSyst.String.Typ'Class;
   procedure set_Embedded(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_UseAttribute(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_XmlNamespace(
      This : access Typ;
      value : access MSSyst.String.Typ'Class);
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_SoapAttribute);
   pragma Import(MSIL,get_Embedded,"get_Embedded");
   pragma Import(MSIL,get_UseAttribute,"get_UseAttribute");
   pragma Import(MSIL,get_XmlNamespace,"get_XmlNamespace");
   pragma Import(MSIL,set_Embedded,"set_Embedded");
   pragma Import(MSIL,set_UseAttribute,"set_UseAttribute");
   pragma Import(MSIL,set_XmlNamespace,"set_XmlNamespace");
end MSSyst.Runtime.Remoting.Metadata.SoapAttribute;
pragma Import(MSIL,MSSyst.Runtime.Remoting.Metadata.SoapAttribute,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Runtime.Remoting.Metadata.SoapAttribute");
