-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.ActivationContext;
limited with MSSyst.ApplicationIdentity;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Runtime.Hosting.ActivationArguments is
   type Typ is new MSSyst.Object.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_ActivationArguments(
      This : Ref := null;
      applicationIdentity : access MSSyst.ApplicationIdentity.Typ'Class) return Ref;
   function new_ActivationArguments(
      This : Ref := null;
      applicationIdentity : access MSSyst.ApplicationIdentity.Typ'Class;
      activationData : access MSSyst.String.Ref_arr) return Ref;
   function new_ActivationArguments(
      This : Ref := null;
      activationData : access MSSyst.ActivationContext.Typ'Class) return Ref;
   function new_ActivationArguments(
      This : Ref := null;
      activationContext : access MSSyst.ActivationContext.Typ'Class;
      activationData : access MSSyst.String.Ref_arr) return Ref;
   function get_ActivationContext(
      This : access Typ) return access MSSyst.ActivationContext.Typ'Class;
   function get_ActivationData(
      This : access Typ) return access MSSyst.String.Ref_arr;
   function get_ApplicationIdentity(
      This : access Typ) return access MSSyst.ApplicationIdentity.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_ActivationArguments);
   pragma Import(MSIL,get_ActivationContext,"get_ActivationContext");
   pragma Import(MSIL,get_ActivationData,"get_ActivationData");
   pragma Import(MSIL,get_ApplicationIdentity,"get_ApplicationIdentity");
end MSSyst.Runtime.Hosting.ActivationArguments;
pragma Import(MSIL,MSSyst.Runtime.Hosting.ActivationArguments,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Runtime.Hosting.ActivationArguments");
