-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.ComponentModel.Design.CommandID;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Windows.Forms.PropertyGridInternal.PropertyGridCommands is
   type Typ is new MSSyst.Object.Typ   with record
      null;
   end record;
   Reset : access MSSyst.ComponentModel.Design.CommandID.Typ'Class;
   pragma Import(MSIL,Reset,"Reset");
   Description : access MSSyst.ComponentModel.Design.CommandID.Typ'Class;
   pragma Import(MSIL,Description,"Description");
   Hide : access MSSyst.ComponentModel.Design.CommandID.Typ'Class;
   pragma Import(MSIL,Hide,"Hide");
   Commands : access MSSyst.ComponentModel.Design.CommandID.Typ'Class;
   pragma Import(MSIL,Commands,"Commands");
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_PropertyGridCommands(
      This : Ref := null) return Ref;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_PropertyGridCommands);
end MSSyst.Windows.Forms.PropertyGridInternal.PropertyGridCommands;
pragma Import(MSIL,MSSyst.Windows.Forms.PropertyGridInternal.PropertyGridCommands,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.PropertyGridInternal.PropertyGridCommands");
