-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Nullable is
   type Typ is abstract new MSSyst.Object.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function GetUnderlyingType(
      nullableType : access MSSyst.Type_k.Typ'Class) return access MSSyst.Type_k.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma Import(MSIL,GetUnderlyingType,"GetUnderlyingType");
end MSSyst.Nullable;
pragma Import(MSIL,MSSyst.Nullable,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Nullable");
