-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.IFormatProvider;
limited with MSSyst.String;
limited with MSSyst.Type_k;
with MSSyst.ValueType;
package MSSyst.Guid is
   type ValueType is new MSSyst.ValueType.Typ with null record;
   type ValueType_Arr is array (Natural range <>) of ValueType; -- start at 0
   type ValueType_Array is access all ValueType_Arr;
   type ValueType_addrof is access all ValueType;
   type ValueType_array_addrof is access all ValueType_Array;
   function new_Guid(
      b : MSIL_Types.unsigned_int8_Arr) return Valuetype;
   function new_Guid(
      a : MSIL_Types.Unsigned_Integer;
      b : MSIL_Types.unsigned_int16;
      c : MSIL_Types.unsigned_int16;
      d : MSIL_Types.unsigned_int8;
      e : MSIL_Types.unsigned_int8;
      f : MSIL_Types.unsigned_int8;
      g : MSIL_Types.unsigned_int8;
      h : MSIL_Types.unsigned_int8;
      i : MSIL_Types.unsigned_int8;
      j : MSIL_Types.unsigned_int8;
      k : MSIL_Types.unsigned_int8) return Valuetype;
   function new_Guid(
      g : access MSSyst.String.Typ'Class) return Valuetype;
   function new_Guid(
      a : Integer;
      b : MSIL_Types.int16;
      c : MSIL_Types.int16;
      d : MSIL_Types.unsigned_int8_Arr) return Valuetype;
   function new_Guid(
      a : Integer;
      b : MSIL_Types.int16;
      c : MSIL_Types.int16;
      d : MSIL_Types.unsigned_int8;
      e : MSIL_Types.unsigned_int8;
      f : MSIL_Types.unsigned_int8;
      g : MSIL_Types.unsigned_int8;
      h : MSIL_Types.unsigned_int8;
      i : MSIL_Types.unsigned_int8;
      j : MSIL_Types.unsigned_int8;
      k : MSIL_Types.unsigned_int8) return Valuetype;
   function CompareTo(
      This : Valuetype;
      value : access MSSyst.Object.Typ'Class) return Integer;
   function CompareTo(
      This : Valuetype;
      value : MSSyst.Guid.Valuetype) return Integer;
   function Equals(
      This : Valuetype;
      g : MSSyst.Guid.Valuetype) return Standard.Boolean;
   function Equals(
      This : Valuetype;
      o : access MSSyst.Object.Typ'Class) return Standard.Boolean;
   function GetHashCode(
      This : Valuetype) return Integer;
   function NewGuid return MSSyst.Guid.Valuetype;
   function op_Equality(
      a : MSSyst.Guid.Valuetype;
      b : MSSyst.Guid.Valuetype) return Standard.Boolean;
   function op_Inequality(
      a : MSSyst.Guid.Valuetype;
      b : MSSyst.Guid.Valuetype) return Standard.Boolean;
   function ToByteArray(
      This : Valuetype) return MSIL_Types.unsigned_int8_Array;
   function ToString(
      This : Valuetype) return access MSSyst.String.Typ'Class;
   function ToString(
      This : Valuetype;
      format : access MSSyst.String.Typ'Class;
      provider : access MSSyst.IFormatProvider.Typ'Class) return access MSSyst.String.Typ'Class;
   function ToString(
      This : Valuetype;
      format : access MSSyst.String.Typ'Class) return access MSSyst.String.Typ'Class;
private
   pragma MSIL_Constructor(new_Guid);
   pragma Import(MSIL,CompareTo,"CompareTo");
   pragma Import(MSIL,Equals,"Equals");
   pragma Import(MSIL,GetHashCode,"GetHashCode");
   pragma Import(MSIL,NewGuid,"NewGuid");
   pragma Import(MSIL,op_Equality,"op_Equality");
   pragma Import(MSIL,op_Inequality,"op_Inequality");
   pragma Import(MSIL,ToByteArray,"ToByteArray");
   pragma Import(MSIL,ToString,"ToString");
end MSSyst.Guid;
pragma Import(MSIL,MSSyst.Guid,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Guid");
