-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Windows.Forms.NativeMethods.RECT;
with MSSyst.Windows.Forms.UnsafeNativeMethods;
limited with MSSyst.Windows.Forms.UnsafeNativeMethods.IOleInPlaceSite;
limited with MSSyst.Windows.Forms.UnsafeNativeMethods.IStream;
package MSSyst.Windows.Forms.UnsafeNativeMethods.IOleDocumentView is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure ApplyViewState(
      This : access Typ;
      pstm : access MSSyst.Windows.Forms.UnsafeNativeMethods.IStream.Typ'Class) is abstract;
   procedure Clone(
      This : access Typ;
      pIPSiteNew : access MSSyst.Windows.Forms.UnsafeNativeMethods.IOleInPlaceSite.Typ'Class;
      ppViewNew : access MSSyst.Windows.Forms.UnsafeNativeMethods.IOleDocumentView.Ref_arr) is abstract;
   function Close(
      This : access Typ;
      dwReserved : Integer) return Integer is abstract;
   function GetDocument(
      This : access Typ) return access MSSyst.Object.Typ'Class is abstract;
   function GetInPlaceSite(
      This : access Typ) return access MSSyst.Windows.Forms.UnsafeNativeMethods.IOleInPlaceSite.Typ'Class is abstract;
   procedure GetRect(
      This : access Typ;
      prcView : access MSSyst.Windows.Forms.NativeMethods.RECT.Valuetype) is abstract;
   procedure Open(
      This : access Typ) is abstract;
   procedure SaveViewState(
      This : access Typ;
      pstm : access MSSyst.Windows.Forms.UnsafeNativeMethods.IStream.Typ'Class) is abstract;
   procedure SetInPlaceSite(
      This : access Typ;
      pIPSite : access MSSyst.Windows.Forms.UnsafeNativeMethods.IOleInPlaceSite.Typ'Class) is abstract;
   procedure SetRect(
      This : access Typ;
      prcView : access MSSyst.Windows.Forms.NativeMethods.RECT.Valuetype) is abstract;
   procedure SetRectComplex(
      This : access Typ;
      prcView : MSSyst.Windows.Forms.NativeMethods.RECT.Valuetype;
      prcHScroll : MSSyst.Windows.Forms.NativeMethods.RECT.Valuetype;
      prcVScroll : MSSyst.Windows.Forms.NativeMethods.RECT.Valuetype;
      prcSizeBox : MSSyst.Windows.Forms.NativeMethods.RECT.Valuetype) is abstract;
   procedure Show(
      This : access Typ;
      fShow : Standard.Boolean) is abstract;
   function UIActivate(
      This : access Typ;
      fUIActivate : Standard.Boolean) return Integer is abstract;
private
   pragma Import(MSIL,ApplyViewState,"ApplyViewState");
   pragma Import(MSIL,Clone,"Clone");
   pragma Import(MSIL,Close,"Close");
   pragma Import(MSIL,GetDocument,"GetDocument");
   pragma Import(MSIL,GetInPlaceSite,"GetInPlaceSite");
   pragma Import(MSIL,GetRect,"GetRect");
   pragma Import(MSIL,Open,"Open");
   pragma Import(MSIL,SaveViewState,"SaveViewState");
   pragma Import(MSIL,SetInPlaceSite,"SetInPlaceSite");
   pragma Import(MSIL,SetRect,"SetRect");
   pragma Import(MSIL,SetRectComplex,"SetRectComplex");
   pragma Import(MSIL,Show,"Show");
   pragma Import(MSIL,UIActivate,"UIActivate");
end MSSyst.Windows.Forms.UnsafeNativeMethods.IOleDocumentView;
pragma Import(MSIL,MSSyst.Windows.Forms.UnsafeNativeMethods.IOleDocumentView,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.UnsafeNativeMethods/IOleDocumentView");
