-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.Array_k;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package MSSyst.Buffer is
   type Typ is abstract new MSSyst.Object.Typ   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure BlockCopy(
      src : access MSSyst.Array_k.Typ'Class;
      srcOffset : Integer;
      dst : access MSSyst.Array_k.Typ'Class;
      dstOffset : Integer;
      count : Integer);
   function ByteLength(
      array_k : access MSSyst.Array_k.Typ'Class) return Integer;
   function GetByte(
      array_k : access MSSyst.Array_k.Typ'Class;
      index : Integer) return MSIL_Types.unsigned_int8;
   procedure SetByte(
      array_k : access MSSyst.Array_k.Typ'Class;
      index : Integer;
      value : MSIL_Types.unsigned_int8);
private
   pragma Convention(MSIL,Typ);
   pragma Import(MSIL,BlockCopy,"BlockCopy");
   pragma Import(MSIL,ByteLength,"ByteLength");
   pragma Import(MSIL,GetByte,"GetByte");
   pragma Import(MSIL,SetByte,"SetByte");
end MSSyst.Buffer;
pragma Import(MSIL,MSSyst.Buffer,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Buffer");
