-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
with MSSyst.Runtime.Remoting.Channels.IChannel;
limited with MSSyst.String;
package MSSyst.Runtime.Remoting.Channels.IChannelReceiver is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function get_ChannelData(
      This : access Typ) return access MSSyst.Object.Typ'Class is abstract;
   function GetUrlsForUri(
      This : access Typ;
      objectURI : access MSSyst.String.Typ'Class) return access MSSyst.String.Ref_arr is abstract;
   procedure StartListening(
      This : access Typ;
      data : access MSSyst.Object.Typ'Class) is abstract;
   procedure StopListening(
      This : access Typ;
      data : access MSSyst.Object.Typ'Class) is abstract;
private
   pragma Import(MSIL,get_ChannelData,"get_ChannelData");
   pragma Import(MSIL,GetUrlsForUri,"GetUrlsForUri");
   pragma Import(MSIL,StartListening,"StartListening");
   pragma Import(MSIL,StopListening,"StopListening");
end MSSyst.Runtime.Remoting.Channels.IChannelReceiver;
pragma Import(MSIL,MSSyst.Runtime.Remoting.Channels.IChannelReceiver,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[mscorlib]System.Runtime.Remoting.Channels.IChannelReceiver");
