-- Autogenerated by MSIL2Ada v. 2
-- By: Martin C. Carlisle
--     Department of Computer Science
--     US Air Force Academy
--     carlislem@acm.org
with MSSyst.Object;
with MSIL_Types;
use MSIL_Types;
limited with MSSyst.ComponentModel.TypeConverter;
limited with MSSyst.Drawing.Rectangle;
limited with MSSyst.Drawing.Size;
with MSSyst.ICloneable;
with MSSyst.IDisposable;
limited with MSSyst.String;
limited with MSSyst.Type_k;
limited with MSSyst.Windows.Forms.AccessibleObject;
limited with MSSyst.Windows.Forms.ContextMenuStrip;
limited with MSSyst.Windows.Forms.DataGridViewAdvancedBorderStyle;
with MSSyst.Windows.Forms.DataGridViewCell;
limited with MSSyst.Windows.Forms.DataGridViewCellStyle;
limited with MSSyst.Windows.Forms.DataGridViewColumn;
limited with MSSyst.Windows.Forms.DataGridViewDataErrorContexts;
with MSSyst.Windows.Forms.DataGridViewElement;
limited with MSSyst.Windows.Forms.DataGridViewElementStates;
limited with MSSyst.Windows.Forms.DataGridViewImageCellLayout;
limited with MSSyst.Windows.Forms.DataGridViewRow;
limited with MSSyst.Windows.Forms.DataGridView;
limited with MSSyst.Windows.Forms.KeyEventArgs;
package MSSyst.Windows.Forms.DataGridViewImageCell is
   type Typ is new MSSyst.Windows.Forms.DataGridViewCell.Typ
         and MSSyst.ICloneable.Typ
         and MSSyst.IDisposable.Typ
   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array(Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_DataGridViewImageCell(
      This : Ref := null) return Ref;
   function new_DataGridViewImageCell(
      This : Ref := null;
      valueIsIcon : Standard.Boolean) return Ref;
   function Clone(
      This : access Typ) return access MSSyst.Object.Typ'Class;
   function get_DefaultNewRowValue(
      This : access Typ) return access MSSyst.Object.Typ'Class;
   function get_Description(
      This : access Typ) return access MSSyst.String.Typ'Class;
   function get_EditType(
      This : access Typ) return access MSSyst.Type_k.Typ'Class;
   function get_FormattedValueType(
      This : access Typ) return access MSSyst.Type_k.Typ'Class;
   function get_ImageLayout(
      This : access Typ) return MSSyst.Windows.Forms.DataGridViewImageCellLayout.Valuetype;
   function get_ValueIsIcon(
      This : access Typ) return Standard.Boolean;
   function get_ValueType(
      This : access Typ) return access MSSyst.Type_k.Typ'Class;
   procedure set_Description(
      This : access Typ;
      value : access MSSyst.String.Typ'Class);
   procedure set_ImageLayout(
      This : access Typ;
      value : MSSyst.Windows.Forms.DataGridViewImageCellLayout.Valuetype);
   procedure set_ValueIsIcon(
      This : access Typ;
      value : Standard.Boolean);
   procedure set_ValueType(
      This : access Typ;
      value : access MSSyst.Type_k.Typ'Class);
   function ToString(
      This : access Typ) return access MSSyst.String.Typ'Class;
private
   pragma Convention(MSIL,Typ);
   pragma MSIL_Constructor(new_DataGridViewImageCell);
   pragma Import(MSIL,Clone,"Clone");
   pragma Import(MSIL,get_DefaultNewRowValue,"get_DefaultNewRowValue");
   pragma Import(MSIL,get_Description,"get_Description");
   pragma Import(MSIL,get_EditType,"get_EditType");
   pragma Import(MSIL,get_FormattedValueType,"get_FormattedValueType");
   pragma Import(MSIL,get_ImageLayout,"get_ImageLayout");
   pragma Import(MSIL,get_ValueIsIcon,"get_ValueIsIcon");
   pragma Import(MSIL,get_ValueType,"get_ValueType");
   pragma Import(MSIL,set_Description,"set_Description");
   pragma Import(MSIL,set_ImageLayout,"set_ImageLayout");
   pragma Import(MSIL,set_ValueIsIcon,"set_ValueIsIcon");
   pragma Import(MSIL,set_ValueType,"set_ValueType");
   pragma Import(MSIL,ToString,"ToString");
end MSSyst.Windows.Forms.DataGridViewImageCell;
pragma Import(MSIL,MSSyst.Windows.Forms.DataGridViewImageCell,
   ".ver 2:0:0:0 .publickeytoken=( b7 7a 5c 56 19 34 e0 89 )",
   "[System.Windows.Forms]System.Windows.Forms.DataGridViewImageCell");
